package com.spark.ai.config;

import javax.sql.DataSource;
import java.sql.Connection;
import java.util.List;
import java.util.Locale;

public enum DatabaseDialect {
    MYSQL,
    POSTGRESQL,
    H2;

    private static volatile DatabaseDialect currentDialect = H2;

    public static DatabaseDialect from(DataSource dataSource) {
        try (Connection connection = dataSource.getConnection()) {
            String product = connection.getMetaData().getDatabaseProductName();
            if (product != null) {
                String lower = product.toLowerCase(Locale.ROOT);
                if (lower.contains("mysql")) return MYSQL;
                if (lower.contains("postgresql")) return POSTGRESQL;
            }
        } catch (Exception ignored) {
            // Fall through to H2-compatible SQL for tests and unavailable databases.
        }
        return H2;
    }

    public static void setCurrentDialect(DatabaseDialect dialect) {
        currentDialect = dialect;
    }

    public static DatabaseDialect getCurrentDialect() {
        return currentDialect;
    }

    public static String q(String identifier) {
        return currentDialect.quoteIdentifier(identifier);
    }

    private static void assertIdentifier(String identifier, String fieldName) {
        if (identifier == null || identifier.isBlank()) {
            throw new IllegalArgumentException(fieldName + " 不能为空");
        }
        if (identifier.contains("`") || identifier.contains("\"") || identifier.contains(";") || identifier.contains("--")) {
            throw new IllegalArgumentException(fieldName + " 包含非法字符: " + identifier);
        }
    }

    public boolean isMySql() {
        return this == MYSQL;
    }

    public String quote(String identifier) {
        return switch (this) {
            case MYSQL -> "`" + identifier + "`";
            case POSTGRESQL, H2 -> "\"" + identifier + "\"";
        };
    }

    public String quoteIdentifier(String identifier) {
        assertIdentifier(identifier, "identifier");
        return quote(identifier);
    }

    public String bigIntType() {
        return "BIGINT";
    }

    public String createTableSuffix() {
        return this == MYSQL ? " ENGINE=InnoDB DEFAULT CHARSET=utf8mb4" : "";
    }

    public String sqlTypeFromDataType(String dataType, Integer maxLength, Integer precision, Integer scale) {
        return switch (dataType.toLowerCase(Locale.ROOT)) {
            case "int", "integer" -> "INT";
            case "number", "long", "bigint" -> bigIntType();
            case "decimal" -> "DECIMAL(" + (precision != null ? precision : 18) + "," + (scale != null ? scale : 2) + ")";
            case "float", "double" -> "DOUBLE";
            case "boolean", "bool" -> "BOOLEAN";
            case "date" -> "DATE";
            case "datetime", "timestamp" -> (this == MYSQL) ? "DATETIME(6)" : "TIMESTAMP";
            case "time" -> "TIME";
            case "text", "object", "array" -> (this == MYSQL) ? "LONGTEXT" : "TEXT";
            default -> "VARCHAR(" + (maxLength != null ? maxLength : 255) + ")";
        };
    }

    public String columnDefinition(ColumnDefinition column, boolean includePrimaryKey) {
        String definition = quoteIdentifier(column.physicalColumnName()) + " " + column.sqlType();
        switch (this) {
            case MYSQL -> {
                if (!column.nullable() || column.autoIncrement()) {
                    definition += " NOT NULL";
                }
                if (column.autoIncrement()) {
                    definition += " AUTO_INCREMENT";
                }
            }
            case POSTGRESQL -> {
                if (column.autoIncrement()) {
                    definition = quoteIdentifier(column.physicalColumnName()) + " BIGSERIAL";
                    if (includePrimaryKey && column.primaryKey()) {
                        definition += " PRIMARY KEY";
                    }
                    return definition;
                }
                if (!column.nullable()) {
                    definition += " NOT NULL";
                }
            }
            default -> { // H2
                if (column.autoIncrement()) {
                    definition += " GENERATED BY DEFAULT AS IDENTITY";
                }
                if (!column.nullable() && !column.autoIncrement()) {
                    definition += " NOT NULL";
                }
            }
        }
        if (includePrimaryKey && column.primaryKey()) {
            definition += " PRIMARY KEY";
        }
        return definition;
    }

    public String addColumnSql(String tableName, ColumnDefinition column) {
        return "ALTER TABLE " + quoteIdentifier(tableName) + " ADD COLUMN " + columnDefinition(column, false);
    }

    public String addRawColumnSql(String tableName, String columnName, String sqlType) {
        return "ALTER TABLE " + quoteIdentifier(tableName) + " ADD COLUMN " + quoteIdentifier(columnName) + " " + sqlType;
    }

    public String addIdentityPrimaryKeyColumnSql(String tableName, String columnName) {
        return switch (this) {
            case MYSQL -> "ALTER TABLE " + quoteIdentifier(tableName) + " ADD COLUMN " + quoteIdentifier(columnName) + " BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY";
            case POSTGRESQL -> "ALTER TABLE " + quoteIdentifier(tableName) + " ADD COLUMN " + quoteIdentifier(columnName) + " BIGSERIAL PRIMARY KEY";
            default -> "ALTER TABLE " + quoteIdentifier(tableName) + " ADD COLUMN " + quoteIdentifier(columnName) + " BIGINT GENERATED BY DEFAULT AS IDENTITY";
        };
    }

    public String alterColumnTypeSql(String tableName, ExistingColumn existing, ColumnDefinition desired) {
        return switch (this) {
            case MYSQL -> "ALTER TABLE " + quoteIdentifier(tableName) + " MODIFY COLUMN " + columnDefinition(desired, false);
            case POSTGRESQL -> "ALTER TABLE " + quoteIdentifier(tableName) + " ALTER COLUMN " + quoteIdentifier(existing.physicalColumnName()) + " TYPE " + desired.sqlType();
            default -> "ALTER TABLE " + quoteIdentifier(tableName) + " ALTER COLUMN " + quoteIdentifier(existing.physicalColumnName()) + " " + desired.sqlType();
        };
    }

    public String setNotNullSql(String tableName, ExistingColumn existing) {
        String definition = quoteIdentifier(existing.physicalColumnName()) + " " + existing.sqlType() + " NOT NULL";
        return switch (this) {
            case MYSQL -> {
                if (existing.autoIncrement()) {
                    definition += " AUTO_INCREMENT";
                }
                yield "ALTER TABLE " + quoteIdentifier(tableName) + " MODIFY COLUMN " + definition;
            }
            case POSTGRESQL -> "ALTER TABLE " + quoteIdentifier(tableName) + " ALTER COLUMN " + quoteIdentifier(existing.physicalColumnName()) + " SET NOT NULL";
            default -> "ALTER TABLE " + quoteIdentifier(tableName) + " ALTER COLUMN " + quoteIdentifier(existing.physicalColumnName()) + " SET NOT NULL";
        };
    }

    public String setNotNullSql(String tableName, String columnName, String sqlType) {
        return switch (this) {
            case MYSQL -> "ALTER TABLE " + quoteIdentifier(tableName) + " MODIFY COLUMN " + quoteIdentifier(columnName) + " " + sqlType + " NOT NULL";
            case POSTGRESQL -> "ALTER TABLE " + quoteIdentifier(tableName) + " ALTER COLUMN " + quoteIdentifier(columnName) + " SET NOT NULL";
            default -> "ALTER TABLE " + quoteIdentifier(tableName) + " ALTER COLUMN " + quoteIdentifier(columnName) + " SET NOT NULL";
        };
    }

    public String dropColumnSql(String tableName, String columnName) {
        return "ALTER TABLE " + quoteIdentifier(tableName) + " DROP COLUMN " + quoteIdentifier(columnName);
    }

    public String createIndexSql(String tableName, String indexName, List<String> columnNames) {
        String columns = columnNames.stream()
                .map(this::quoteIdentifier)
                .reduce((left, right) -> left + ", " + right)
                .orElse("");
        return "CREATE INDEX " + quoteIdentifier(indexName) + " ON " + quoteIdentifier(tableName) + " (" + columns + ")";
    }

    public String createDatabaseSql(String databaseName, String charset, String collation) {
        return switch (this) {
            case MYSQL -> {
                String sql = "CREATE DATABASE IF NOT EXISTS " + quoteIdentifier(databaseName);
                if (charset != null && !charset.isBlank()) {
                    sql += " CHARACTER SET " + charset;
                }
                if (collation != null && !collation.isBlank()) {
                    sql += " COLLATE " + collation;
                }
                yield sql;
            }
            case POSTGRESQL -> "CREATE DATABASE " + quoteIdentifier(databaseName);
            default -> "CREATE DATABASE " + quoteIdentifier(databaseName);
        };
    }

    public String jdbcUrl(String host, int port, String databaseName) {
        return switch (this) {
            case MYSQL -> "jdbc:mysql://" + host + ":" + port + "/" + databaseName
                    + "?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai";
            case POSTGRESQL -> "jdbc:postgresql://" + host + ":" + port + "/" + databaseName;
            default -> "jdbc:h2:mem:" + databaseName + ";MODE=MySQL";
        };
    }

    public String driverClassName() {
        return switch (this) {
            case MYSQL -> "com.mysql.cj.jdbc.Driver";
            case POSTGRESQL -> "org.postgresql.Driver";
            default -> "org.h2.Driver";
        };
    }

    public record ColumnDefinition(
            String physicalColumnName,
            String sqlType,
            boolean primaryKey,
            boolean autoIncrement,
            boolean nullable
    ) {}

    public record ExistingColumn(
            String physicalColumnName,
            String sqlType,
            boolean autoIncrement
    ) {}
}
