/**
 * 组件层入口。
 *
 * 聚合所有可渲染组件、组件内部注册函数以及少量对外暴露的组件级 composable。
 */

export { default as SparkComponentRenderer } from './SparkComponentRenderer.vue'
export * as componentComposables from './composables.js'
export * as containerComposables from './containers/composables.js'
export * as containerDataComponents from './containers/data-components/index.js'
export * as containerNonDataComponents from './containers/non-data-components/index.js'
export * as containerDataComponentComposables from './containers/data-components/composables/index.js'
export * as containerNonDataComponentComposables from './containers/non-data-components/composables/index.js'
export * as containerDataComponentSupport from './containers/data-components/support/index.js'
export * as containerDataUi from './containers/data-components/index.js'
export * as containerNonDataUi from './containers/non-data-components/index.js'
export * as containerDataUiComposables from './containers/data-components/composables/index.js'
export * as containerNonDataUiComposables from './containers/non-data-components/composables/index.js'
export * as containerActionComposables from './containers/actions/index.js'
export * as containerContextComposables from './containers/context/index.js'
export * as containerDataComposables from './containers/data/index.js'
export * as containerLayoutComposables from './containers/layout/index.js'
export * as fieldComposables from './fields/composables.js'
export * as fieldDataComponents from './fields/data-components/index.js'
export * as fieldNonDataComponents from './fields/non-data-components/index.js'
export * as fieldDataComponentComposables from './fields/data-components/composables/index.js'
export * as fieldNonDataComponentComposables from './fields/non-data-components/composables/index.js'
export * as fieldDataComponentSupport from './fields/data-components/support/index.js'
export * as fieldDataUi from './fields/data-components/index.js'
export * as fieldNonDataUi from './fields/non-data-components/index.js'
export * as fieldDataUiComposables from './fields/data-components/composables/index.js'
export * as fieldNonDataUiComposables from './fields/non-data-components/composables/index.js'
export * as fieldContextComposables from './fields/context/index.js'
export * as fieldOptionComposables from './fields/options/index.js'
export * as fieldActionComposables from './fields/actions/index.js'

// ── 容器组件 ──────────────────────────────────────────────────────────────────
export { default as RendererTable } from './containers/data-components/RendererTable.vue'
export { default as RendererForm } from './containers/data-components/RendererForm.vue'
export { default as RendererDetail } from './containers/data-components/RendererDetail.vue'
export { default as RendererTree } from './containers/data-components/RendererTree.vue'
export { default as RendererList } from './containers/data-components/RendererList.vue'
export { default as RendererTabs } from './containers/non-data-components/RendererTabs.vue'
export { default as RendererCollapse } from './containers/non-data-components/RendererCollapse.vue'
export { default as RendererDialog } from './containers/non-data-components/RendererDialog.vue'
export { default as RendererDrawer } from './containers/non-data-components/RendererDrawer.vue'
export { default as RendererSteps } from './containers/non-data-components/RendererSteps.vue'
export { default as RendererSection } from './containers/non-data-components/RendererSection.vue'
export { default as RendererToolbar } from './containers/non-data-components/RendererToolbar.vue'
export { default as RendererFieldScope } from './containers/data-components/RendererFieldScope.vue'
export { default as RendererListItemScope } from './containers/data-components/RendererListItemScope.vue'

// ── 字段组件 ──────────────────────────────────────────────────────────────────
export { default as FieldText } from './fields/data-components/FieldText.vue'
export { default as FieldTextarea } from './fields/data-components/FieldTextarea.vue'
export { default as FieldHtmlEditor } from './fields/data-components/FieldHtmlEditor.vue'
export { default as FieldNumber } from './fields/data-components/FieldNumber.vue'
export { default as FieldDate } from './fields/data-components/FieldDate.vue'
export { default as FieldSelect } from './fields/data-components/FieldSelect.vue'
export { default as FieldMultiSelect } from './fields/data-components/FieldMultiSelect.vue'
export { default as FieldRadio } from './fields/data-components/FieldRadio.vue'
export { default as FieldCheckbox } from './fields/data-components/FieldCheckbox.vue'
export { default as FieldCheckboxGroup } from './fields/data-components/FieldCheckboxGroup.vue'
export { default as FieldSwitch } from './fields/data-components/FieldSwitch.vue'
export { default as FieldSlider } from './fields/data-components/FieldSlider.vue'
export { default as FieldRate } from './fields/data-components/FieldRate.vue'
export { default as FieldColor } from './fields/data-components/FieldColor.vue'
export { default as FieldIcon } from './fields/data-components/FieldIcon.vue'
export { default as FieldImage } from './fields/data-components/FieldImage.vue'
export { default as FieldFilePath } from './fields/data-components/FieldFilePath.vue'
export { default as FieldFileBrowser } from './fields/data-components/FieldFileBrowser.vue'
export { default as FieldUpload } from './fields/data-components/FieldUpload.vue'
export { default as FieldEntityPicker } from './fields/data-components/FieldEntityPicker.vue'
export { default as FieldUserPicker } from './fields/data-components/FieldUserPicker.vue'
export { default as FieldDeptPicker } from './fields/data-components/FieldDeptPicker.vue'
export { default as FieldProductPicker } from './fields/data-components/FieldProductPicker.vue'
export { default as FieldCascader } from './fields/data-components/FieldCascader.vue'
export { default as FieldTreeSelect } from './fields/data-components/FieldTreeSelect.vue'
export { default as FieldTransfer } from './fields/data-components/FieldTransfer.vue'
export { default as FieldContextRenderer } from './fields/non-data-components/FieldContextRenderer.vue'
export { default as FieldColumnGroup } from './fields/non-data-components/FieldContextRenderer.vue'
export { default as FieldTreeNodeSummary } from './fields/non-data-components/TreeNodeSummary.vue'

export { registerAllRenderers } from './register-renderers.js'
export { useFieldPermission } from './fields/composables.js'
