export type {
  AppModuleBase,
  AppNavRoot,
  AppNavigation,
  ChildPlacement,
  LinkTarget,
  NavContextConfig,
  NavContextInput,
  NavContextItem,
  NavContextState,
  NavNode,
  NavNodeKind,
  NavPermissionMode,
  RegionItems,
  RegionVisibility,
} from '@spark-view/spark-page-config/page/navigation'
