export { SparkPageConfig } from './namespace'

export type {
  ConfigLoaderOptions,
  ConfigLoadResult,
  PageConfig,
  PageConfigFileLoadOptions,
  PageConfigFileName,
  PageConfigFiles,
  PageCssConfig,
  PageDataConfig,
  PageFileRegistry,
  PageScriptConfig,
  RuleConfig,
} from './loading'

export {
  BasePageConfigLoader,
  PAGE_CONFIG_FILE_NAMES,
  PageConfigLoader,
  compileRule,
  createConfigLoader,
  createDefaultFileRegistry,
  normalizeRuleNode,
  parseCss,
  parsePageData,
  parseScript,
} from './loading'

export type {
  AppModuleBase,
  AppNavRoot,
  AppNavigation,
  ChildPlacement,
  LinkProbeResult,
  LinkTarget,
  NavContextConfig,
  NavContextInput,
  NavContextItem,
  NavContextState,
  NavNode,
  NavNodeKind,
  NavNodeLocation,
  NavPermissionMode,
  NavigationConfigClientOptions,
  NavigationContextDraft,
  NavigationContextDraftConfig,
  NavigationNodeDraft,
  NavigationNodeDraftApplyResult,
  NavigationNodeDraftInput,
  RegionItems,
  RegionVisibility,
} from './navigation'

export {
  DEFAULT_NAV_ICON_BY_KIND,
  NavigationConfigClient,
  NavigationEditSession,
  applyNavigationNodeDraftToNode,
  applyNodeKindPresetToDraft,
  buildNavRoot,
  canUseModuleNodeKind,
  createChildPageNode,
  createNavigationNodeDraft,
  createNavigationNodePatch,
  createReservedRootGroup,
  createRootModuleNode,
  defaultNavIconByKind,
  findConfigNodeByPageId,
  findNodeById,
  findNodeLocation,
  findParentNodeById,
  inferNavNodeKind,
  isConfigNodeKind,
  isPageLikeKind,
  isSystemRootDirectory,
  normalizeNavNode,
  normalizeNavRoot,
  normalizePageIdFromPath,
  normalizeRootChildPlacement,
} from './navigation'
