CREATE TABLE IF NOT EXISTS tenant_config (
  tenant_id VARCHAR(64) NOT NULL,
  tenant_name VARCHAR(128),
  tenant_code VARCHAR(64),
  logo VARCHAR(512),
  primary_color VARCHAR(32),
  border_radius VARCHAR(32),
  home_path VARCHAR(256),
  log_level VARCHAR(16),
  api_base_url VARCHAR(256),
  enable_ai BOOLEAN,
  enable_export BOOLEAN,
  enable_offline BOOLEAN,
  config_json LONGTEXT,
  created_at DATETIME(6) NOT NULL,
  updated_at DATETIME(6) NOT NULL,
  PRIMARY KEY (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS app_user (
  id BIGINT NOT NULL AUTO_INCREMENT,
  tenant_id VARCHAR(64) NOT NULL,
  username VARCHAR(128) NOT NULL,
  display_name VARCHAR(128),
  password_hash VARCHAR(256) NOT NULL,
  email VARCHAR(256),
  avatar VARCHAR(512),
  roles VARCHAR(512) NOT NULL,
  enabled BOOLEAN NOT NULL,
  created_at DATETIME(6) NOT NULL,
  updated_at DATETIME(6) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_tenant_username (tenant_id, username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS project (
  id BIGINT NOT NULL AUTO_INCREMENT,
  tenant_id VARCHAR(64) NOT NULL,
  project_id VARCHAR(64) NOT NULL,
  name VARCHAR(256) NOT NULL,
  project_type VARCHAR(16) NOT NULL,
  icon VARCHAR(64),
  description VARCHAR(1024),
  sort_order INT NOT NULL,
  created_at DATETIME(6) NOT NULL,
  updated_at DATETIME(6) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_tenant_project (tenant_id, project_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS project_member (
  id BIGINT NOT NULL AUTO_INCREMENT,
  tenant_id VARCHAR(64) NOT NULL,
  project_id VARCHAR(64) NOT NULL,
  username VARCHAR(128) NOT NULL,
  role VARCHAR(64) NOT NULL,
  created_at DATETIME(6) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_project_member (tenant_id, project_id, username),
  KEY idx_project_member_user (tenant_id, username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT IGNORE INTO project_member (tenant_id, project_id, username, role, created_at)
SELECT p.tenant_id, p.project_id, u.username,
       CASE WHEN FIND_IN_SET('admin', u.roles) > 0 THEN 'owner' ELSE 'member' END,
       CURRENT_TIMESTAMP(6)
FROM project p
JOIN app_user u ON u.tenant_id = p.tenant_id;

CREATE TABLE IF NOT EXISTS file_version (
  id BIGINT NOT NULL AUTO_INCREMENT,
  tenant_id VARCHAR(64) NOT NULL,
  project_id VARCHAR(64) NOT NULL,
  page_id VARCHAR(128) NOT NULL,
  filename VARCHAR(64) NOT NULL,
  version INT NOT NULL,
  is_current BOOLEAN NOT NULL,
  modified_by VARCHAR(128),
  source VARCHAR(64),
  commit_message VARCHAR(1024),
  approval_status VARCHAR(64),
  ai_session_id VARCHAR(128),
  ai_turn_id VARCHAR(128),
  request_id VARCHAR(128),
  content_hash VARCHAR(128),
  storage_ref VARCHAR(1024),
  created_at DATETIME(6) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_file_version (tenant_id, project_id, page_id, filename, version),
  KEY idx_file_version_scope (tenant_id, project_id, page_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS page_config_file (
  id BIGINT NOT NULL AUTO_INCREMENT,
  tenant_id VARCHAR(64) NOT NULL,
  project_id VARCHAR(64) NOT NULL,
  page_id VARCHAR(128) NOT NULL,
  filename VARCHAR(128) NOT NULL,
  content LONGTEXT NOT NULL,
  updated_at DATETIME(6) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_page_config_file (tenant_id, project_id, page_id, filename)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ai_session (
  session_id VARCHAR(128) NOT NULL,
  tenant_id VARCHAR(64),
  project_id VARCHAR(64),
  username VARCHAR(128),
  system_prompt LONGTEXT,
  mode VARCHAR(64),
  state VARCHAR(64),
  scope_json LONGTEXT,
  tools_json LONGTEXT,
  window_size INT NOT NULL,
  created_at DATETIME(6) NOT NULL,
  updated_at DATETIME(6) NOT NULL,
  last_active_at DATETIME(6),
  expires_at DATETIME(6),
  PRIMARY KEY (session_id),
  KEY idx_ai_session_scope (tenant_id, project_id, updated_at),
  KEY idx_ai_session_expires_at (expires_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ai_message (
  id BIGINT NOT NULL AUTO_INCREMENT,
  session_id VARCHAR(128) NOT NULL,
  seq_no INT NOT NULL,
  role VARCHAR(64) NOT NULL,
  content LONGTEXT,
  tool_call_id VARCHAR(255),
  tool_calls_json LONGTEXT,
  created_at DATETIME(6) NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_ai_message_seq (session_id, seq_no),
  KEY idx_ai_message_session (session_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ai_tool_call (
  id BIGINT NOT NULL AUTO_INCREMENT,
  session_id VARCHAR(128) NOT NULL,
  turn_id VARCHAR(128),
  call_id VARCHAR(255),
  name VARCHAR(255),
  arguments_json LONGTEXT,
  status VARCHAR(64),
  runtime_meta_json LONGTEXT,
  created_at DATETIME(6) NOT NULL,
  PRIMARY KEY (id),
  KEY idx_ai_tool_call_session (session_id),
  KEY idx_ai_tool_call_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ai_context_snapshot (
  id BIGINT NOT NULL AUTO_INCREMENT,
  session_id VARCHAR(128) NOT NULL,
  turn_id VARCHAR(128),
  scope_json LONGTEXT,
  created_at DATETIME(6) NOT NULL,
  PRIMARY KEY (id),
  KEY idx_ai_context_session (session_id),
  KEY idx_ai_context_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS NAVIGATION_NODE_FLAT (
  NODE_ID VARCHAR(255) NOT NULL,
  PARENT_ID VARCHAR(255),
  TENANT_ID VARCHAR(255) NOT NULL,
  PROJECT_ID VARCHAR(255) NOT NULL,
  TITLE VARCHAR(500),
  DESCRIPTION VARCHAR(2000),
  NODE_KIND VARCHAR(50),
  PATH VARCHAR(500),
  ICON VARCHAR(255),
  DIVIDER_AFTER BOOLEAN DEFAULT FALSE,
  CHILD_PLACEMENT VARCHAR(50),
  LINK_TARGET VARCHAR(50),
  HIDDEN BOOLEAN DEFAULT FALSE,
  DISABLED BOOLEAN DEFAULT FALSE,
  SORT_ORDER INT DEFAULT 0,
  UPDATED_AT DATETIME(6),
  REF_ID VARCHAR(255),
  CONTEXT LONGTEXT,
  PERMISSIONS VARCHAR(2000),
  PRIMARY KEY (NODE_ID),
  KEY IDX_NAV_TENANT_PROJECT (TENANT_ID, PROJECT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS FILTER_EXPRESSION_CASE (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  TENANT_ID VARCHAR(255) NOT NULL,
  PROJECT_ID VARCHAR(255) NOT NULL,
  TITLE VARCHAR(255) NOT NULL,
  STATUS VARCHAR(64) NOT NULL,
  PRIORITY INT NOT NULL,
  AMOUNT DECIMAL(18,2) NOT NULL,
  THRESHOLD DECIMAL(18,2) NOT NULL,
  CATEGORY VARCHAR(64),
  CREATED_AT DATETIME(6) NOT NULL,
  UPDATED_AT DATETIME(6) NOT NULL,
  PRIMARY KEY (ID),
  KEY IDX_FILTER_EXPR_CASE_SCOPE (TENANT_ID, PROJECT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS DATA_MODEL_TABLE (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  TENANT_ID VARCHAR(255) NOT NULL,
  PROJECT_ID VARCHAR(255) NOT NULL,
  LOGICAL_TABLE_NAME VARCHAR(255) NOT NULL,
  ORIGIN VARCHAR(64) NOT NULL,
  MANAGED_MODE VARCHAR(64) NOT NULL,
  PHYSICAL_TABLE_NAME VARCHAR(255) NOT NULL,
  PRIMARY_KEY_FIELD VARCHAR(255) NOT NULL,
  RESOURCE_TYPE VARCHAR(64),
  RESOURCE_ID VARCHAR(255),
  BUSINESS_CATEGORY VARCHAR(64),
  SCHEMA_VERSION INT NOT NULL DEFAULT 1,
  DDL_HASH VARCHAR(128),
  STATUS VARCHAR(64) NOT NULL DEFAULT 'active',
  LAST_INTROSPECTED_AT DATETIME(6),
  CREATED_AT DATETIME(6) NOT NULL,
  UPDATED_AT DATETIME(6) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY uk_data_model_table_scope (TENANT_ID, PROJECT_ID, LOGICAL_TABLE_NAME),
  KEY IDX_DATA_MODEL_TABLE_SCOPE (TENANT_ID, PROJECT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS DATA_MODEL_COLUMN (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  TABLE_ID BIGINT NOT NULL,
  COLUMN_NAME VARCHAR(255) NOT NULL,
  PHYSICAL_COLUMN_NAME VARCHAR(255) NOT NULL,
  DATA_TYPE VARCHAR(64) NOT NULL,
  SQL_TYPE VARCHAR(255) NOT NULL,
  ORDINAL_POSITION INT NOT NULL,
  IS_PRIMARY_KEY BOOLEAN NOT NULL DEFAULT FALSE,
  IS_AUTO_INCREMENT BOOLEAN NOT NULL DEFAULT FALSE,
  IS_NULLABLE BOOLEAN NOT NULL DEFAULT TRUE,
  IS_REQUIRED BOOLEAN NOT NULL DEFAULT FALSE,
  MAX_LENGTH INT,
  NUMERIC_PRECISION INT,
  NUMERIC_SCALE INT,
  DEFAULT_VALUE VARCHAR(2000),
  LABEL VARCHAR(255),
  CREATED_AT DATETIME(6) NOT NULL,
  UPDATED_AT DATETIME(6) NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY uk_data_model_column (TABLE_ID, COLUMN_NAME),
  KEY IDX_DATA_MODEL_COLUMN_TABLE (TABLE_ID, ORDINAL_POSITION)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS DATA_BATCH_JOB (
  JOB_ID VARCHAR(64) NOT NULL,
  TENANT_ID VARCHAR(255) NOT NULL,
  PROJECT_ID VARCHAR(255) NOT NULL,
  REQUEST_ID VARCHAR(255),
  STATUS VARCHAR(64) NOT NULL,
  TOTAL_COUNT INT NOT NULL DEFAULT 0,
  COMPLETED_COUNT INT NOT NULL DEFAULT 0,
  SUCCESS_COUNT INT NOT NULL DEFAULT 0,
  FAILURE_COUNT INT NOT NULL DEFAULT 0,
  PAYLOAD LONGTEXT,
  RESULT LONGTEXT,
  ERROR_MESSAGE LONGTEXT,
  CREATED_AT DATETIME(6) NOT NULL,
  UPDATED_AT DATETIME(6) NOT NULL,
  COMPLETED_AT DATETIME(6),
  PRIMARY KEY (JOB_ID),
  KEY IDX_DATA_BATCH_JOB_SCOPE (TENANT_ID, PROJECT_ID, CREATED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS DATA_BATCH_JOB_ITEM (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  JOB_ID VARCHAR(64) NOT NULL,
  OPERATION_ID VARCHAR(255),
  TABLE_NAME VARCHAR(255) NOT NULL,
  OPERATION VARCHAR(64) NOT NULL,
  STATUS VARCHAR(64) NOT NULL,
  PAYLOAD LONGTEXT,
  RESULT LONGTEXT,
  ERROR_MESSAGE LONGTEXT,
  CREATED_AT DATETIME(6) NOT NULL,
  UPDATED_AT DATETIME(6) NOT NULL,
  PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS DATA_TRANSACTION_COMMIT (
  TRANSACTION_ID VARCHAR(64) NOT NULL,
  TENANT_ID VARCHAR(255) NOT NULL,
  PROJECT_ID VARCHAR(255) NOT NULL,
  REQUEST_ID VARCHAR(255) NOT NULL,
  REQUEST_HASH VARCHAR(128) NOT NULL,
  STATUS VARCHAR(64) NOT NULL,
  PAYLOAD LONGTEXT,
  RESULT LONGTEXT,
  CREATED_AT DATETIME(6) NOT NULL,
  UPDATED_AT DATETIME(6) NOT NULL,
  COMPLETED_AT DATETIME(6),
  PRIMARY KEY (TRANSACTION_ID),
  UNIQUE KEY uk_data_transaction_commit_request (TENANT_ID, PROJECT_ID, REQUEST_ID),
  KEY IDX_DATA_TRANSACTION_COMMIT_SCOPE (TENANT_ID, PROJECT_ID, CREATED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
