-- V2: 多层级数据源元数据管理
-- Server → Database → Table → Relation 层级体系
-- Flyway 保证本脚本仅执行一次，故不需要 IF NOT EXISTS 防护

-- 1. 服务器注册表（全局，不强制绑定租户）
CREATE TABLE DATA_SOURCE_SERVER (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    SERVER_NAME VARCHAR(255) NOT NULL,
    HOST VARCHAR(255) NOT NULL,
    PORT INT NOT NULL,
    DB_TYPE VARCHAR(64) NOT NULL DEFAULT 'mysql',
    USERNAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(512) NOT NULL,
    ISOLATION_MODE VARCHAR(32) NOT NULL DEFAULT 'TENANT_ISOLATED',
    TENANT_ID VARCHAR(255),
    CREATED_BY VARCHAR(255),
    STATUS VARCHAR(64) NOT NULL DEFAULT 'active',
    CREATED_AT DATETIME(6) NOT NULL,
    UPDATED_AT DATETIME(6) NOT NULL,
    PRIMARY KEY (ID),
    KEY IDX_DSS_ISOLATION (ISOLATION_MODE, TENANT_ID),
    KEY IDX_DSS_STATUS (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2. 数据库注册表（绑定租户+项目）
CREATE TABLE DATA_SOURCE_DATABASE (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    SERVER_ID BIGINT NOT NULL,
    DATABASE_NAME VARCHAR(255) NOT NULL,
    ISOLATION_MODE VARCHAR(32) NOT NULL DEFAULT 'TENANT_ISOLATED',
    TENANT_ID VARCHAR(255) NOT NULL,
    PROJECT_ID VARCHAR(255),
    CREATED_BY VARCHAR(255),
    STATUS VARCHAR(64) NOT NULL DEFAULT 'active',
    CREATED_AT DATETIME(6) NOT NULL,
    UPDATED_AT DATETIME(6) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (SERVER_ID) REFERENCES DATA_SOURCE_SERVER(ID) ON DELETE RESTRICT,
    UNIQUE KEY uk_dsd_scope (TENANT_ID, PROJECT_ID, DATABASE_NAME),
    KEY IDX_DSD_SERVER (SERVER_ID),
    KEY IDX_DSD_TENANT (TENANT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 3. DATA_MODEL_TABLE 增加 DATABASE_ID 和 ISOLATION_MODE
ALTER TABLE DATA_MODEL_TABLE
    ADD COLUMN DATABASE_ID BIGINT,
    ADD COLUMN ISOLATION_MODE VARCHAR(32) NOT NULL DEFAULT 'PROJECT_ISOLATED',
    ADD FOREIGN KEY fk_dmt_database (DATABASE_ID) REFERENCES DATA_SOURCE_DATABASE(ID) ON DELETE SET NULL,
    ADD KEY IDX_DMT_DATABASE (DATABASE_ID);

-- 4. 表关系定义
CREATE TABLE DATA_MODEL_RELATION (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    PARENT_TABLE_ID BIGINT NOT NULL,
    CHILD_TABLE_ID BIGINT NOT NULL,
    PARENT_FIELD VARCHAR(255) NOT NULL,
    CHILD_FIELD VARCHAR(255) NOT NULL,
    RELATION_NAME VARCHAR(255),
    CREATED_AT DATETIME(6) NOT NULL,
    UPDATED_AT DATETIME(6) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (PARENT_TABLE_ID) REFERENCES DATA_MODEL_TABLE(ID) ON DELETE CASCADE,
    FOREIGN KEY (CHILD_TABLE_ID) REFERENCES DATA_MODEL_TABLE(ID) ON DELETE CASCADE,
    UNIQUE KEY uk_dmr_relation (PARENT_TABLE_ID, CHILD_TABLE_ID, PARENT_FIELD, CHILD_FIELD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 5. 历史动态表继续使用主库：DATABASE_ID 保持 NULL。
-- 不写入默认服务器/数据库，避免空密码元数据被 DynamicDataSourceManager 当成真实外部库解密和连接。
