-- V5: DBMS physical-object identity.
-- Logical table/column names become editable aliases; DBMS lookup and sync use physical keys.

ALTER TABLE DATA_MODEL_TABLE
    ADD COLUMN OBJECT_TYPE VARCHAR(16) NOT NULL DEFAULT 'TABLE',
    ADD COLUMN SCHEMA_NAME VARCHAR(255) NOT NULL DEFAULT '';

ALTER TABLE DATA_MODEL_TABLE
    DROP INDEX uk_data_model_table_scope,
    ADD UNIQUE KEY uk_dmt_physical_object (DATABASE_ID, OBJECT_TYPE, SCHEMA_NAME, PHYSICAL_TABLE_NAME),
    ADD KEY IDX_DMT_LOGICAL_ALIAS (TENANT_ID, PROJECT_ID, LOGICAL_TABLE_NAME);

ALTER TABLE DATA_MODEL_COLUMN
    DROP INDEX uk_data_model_column,
    ADD UNIQUE KEY uk_dmc_physical_column (TABLE_ID, PHYSICAL_COLUMN_NAME),
    ADD KEY IDX_DMC_ALIAS (TABLE_ID, COLUMN_NAME);
