/**
 * @spark-view/spark-page-config
 *
 * SPARK 页面配置层 - L2 业务编排层
 * 支持页面配置文件 API 加载、动态路由注册、配置缓存和验证
 */

// 类型导出
export type {
  SparkNode,
  SparkNodeChildren,
  RuleConfig,
  PageDataConfig,
  PageScriptConfig,
  PageCssConfig,
  PageConfigFiles,
  PageConfigFileName,
  PageConfigFileLoadOptions,
  PageConfig,
  ConfigLoaderOptions,
  ConfigLoadResult,
} from './types'

export {
  BasePageConfigLoader,
  PAGE_CONFIG_FILE_NAMES,
} from './types'

export {
  SPARK_NODE_STRUCT_KEYS,
  normalizeSparkNode,
  nodeId,
  nodeInputProp,
  nodeInputProps,
  isSparkNode,
  getSparkNodeChildren,
} from './spark-node'

export type {
  SparkNodeTreeJsonInput,
  SparkNodeTreeRuleJsonInput,
  SparkNodeTreeRootParams,
  SparkNodeTreeFromJsonOptions,
  SparkNodeTreeLookupParams,
  SparkNodeTreeChildrenParams,
  SparkNodeTreeAddParams,
  SparkNodeTreeAddNodesParams,
  SparkNodeTreeMoveParams,
  SparkNodeTreeSetPropsParams,
  SparkNodeTreeSetPropsBatchItem,
  SparkNodeTreeSetPropsBatchParams,
  SparkNodeTreeReplaceParams,
  SparkNodeTreeReplaceNodesItem,
  SparkNodeTreeReplaceNodesParams,
  SparkNodeTreeRemoveParams,
  SparkNodeTreeRemoveNodesParams,
  SparkNodeTreeMethodKey,
  SparkNodeLocation,
  SparkNodeAddResult,
  SparkNodeAddNodesResult,
  SparkNodeMoveResult,
  SparkNodeSetPropsResult,
  SparkNodeSetPropsBatchResult,
  SparkNodeReplaceResult,
  SparkNodeReplaceNodesResult,
  SparkNodeRemoveResult,
  SparkNodeRemoveNodesResult,
  SparkNodeFindByTypeParams,
  SparkNodeFindByTypeMatch,
  SparkNodeFindByTypeResult,
} from './spark-node-tree'

export {
  SparkNodeTree,
  SPARK_PAGE_NODE_TYPE,
  SPARK_PAGE_ROOT_ID,
} from './spark-node-tree'

export type {
  AutoPopulateEntry,
  CreateMountedPageParams,
  CreateMountedPageResult,
  DesignerColumnProjection,
  DesignerRelationProjection,
  DesignerTableProjection,
  DesignerTableUiState,
  DynamicPageFileDocument,
  FlatJsonTreeDocument,
  JsonDocument,
  JsonNodeType,
  JsonObject,
  JsonPath,
  JsonPathSegment,
  JsonSchemaInfo,
  JsonTreePolicy,
  JsonValue,
  LayoutForNewTable,
  LoadFromTextOptions,
  MutationResult,
  PageConfigCreatePageParams,
  PageConfigEditWorkspaceOptions,
  PageConfigFileApiOptions,
  PageConfigFileLifecycleOptions,
  PageConfigFileVersionSummary,
  PageConfigPageSummary,
  PageDataEditorMode,
  PageDesignEditHost,
  PageDesignEditHostSnapshot,
  PageDesignEditPhase,
  PageDesignFlowDescription,
  PageDesignFlowPhaseSummary,
  PageDesignFlowQuery,
  PageDesignFlowStep,
  PageDesignNodeTree,
  PageDesignServiceContext,
  PageDesignServiceMethodBinding,
  PageDesignServiceOptions,
  PageDesignServiceResult,
  PageDesignServiceState,
  PageDesignTextFileKey,
  PageDocumentRegistry,
  PageFileDocument,
  PageFileLoadState,
  PageFileName,
  PageNavigationMountParams,
  RemoveMountedPageParams,
  RemoveMountedPageResult,
  RuleEditorComponentMetadata,
  TreeDisplayNode,
  TreeModel,
  TreeNode,
} from './files'

export {
  EMPTY_RULE_EDITOR_COMPONENT_METADATA,
  PAGE_DATA_JSON_SCHEMA,
  PAGE_DESIGN_100_STEP_FLOW,
  PAGE_FILE_NAMES,
  PageConfigEditWorkspace,
  PageConfigFileApi,
  PageConfigFileLifecycle,
  PageConfigLoader,
  PageDesignEditSession,
  PageDesignService,
  addChildNode,
  addSiblingNode,
  applyAutoPopulatePatches,
  buildDataSetMetadataFromDesignerProjection,
  buildJsonTreeRows,
  buildTreeModel,
  canUseStructuredPageDataEditor,
  canonicalizePageDataJson,
  canonicalizePageDataValue,
  compileRule,
  createConfigLoader,
  createPageDocuments,
  createPageDocumentsFromRegistry,
  createRuleJsonSchema,
  createRuleTreePolicy,
  deleteNode,
  ensureUniqueObjectKey,
  exportJsonDocument,
  filterTreeNodes,
  flattenJsonDocumentForEdit,
  forEachDocument,
  forEachDynamicDocument,
  formatJsonPath,
  formatValuePreview,
  getNextPageDesignFlowStep,
  getNodePath,
  getPageDesignFlowStep,
  getValueAtJsonPath,
  hasDesignerProjectionChanges,
  isJsonObject,
  isPageDesignServiceResult,
  isPageFileDocumentDirty,
  listPageDesignFlowSteps,
  normalizeJsonDocument,
  normalizeRuleNode,
  pageDesignServiceFailure,
  parseCss,
  parseJsonDocument,
  parsePageData,
  parseScript,
  projectDesignerRelations,
  projectDesignerTables,
  reconcileDesignerTableUiState,
  registerPageDesignEditHost,
  renameNodeKey,
  resolvePageDesignEditHost,
  resolvePageDesignEditPageId,
  resolveSchemaInfoForPath,
  restoreJsonDocumentByOriginalType,
  restoreJsonDocumentFromFlat,
  rootOf,
  serializeJsonDocument,
  summarizePageDesignFlowPhases,
  toDisplayRows,
  updateNodeType,
  updateNodeValue,
} from './files'

export {
  registerAppAiBusinesses,
} from './ai/registrations'

export type {
  RegisterAppAiBusinessesOptions,
} from './ai/registrations'

export type {
  AppModuleBase,
  AppNavRoot,
  AppNavigation,
  ChildPlacement,
  LinkProbeResult,
  LinkTarget,
  NavContextConfig,
  NavContextInput,
  NavContextItem,
  NavContextState,
  NavNode,
  NavNodeKind,
  NavNodeLocation,
  NavPermissionMode,
  NavigationConfigClientOptions,
  NavigationContextDraft,
  NavigationContextDraftConfig,
  NavigationNodeDraft,
  NavigationNodeDraftApplyResult,
  NavigationNodeDraftInput,
  RegionItems,
  RegionVisibility,
} from './navigation'

export {
  DEFAULT_NAV_ICON_BY_KIND,
  NavigationConfigClient,
  NavigationEditSession,
  applyNavigationNodeDraftToNode,
  applyNodeKindPresetToDraft,
  buildNavRoot,
  canUseModuleNodeKind,
  createChildPageNode,
  createNavigationNodeDraft,
  createNavigationNodePatch,
  createReservedRootGroup,
  createRootModuleNode,
  defaultNavIconByKind,
  findConfigNodeByPageId,
  findNodeById,
  findNodeLocation,
  findParentNodeById,
  inferNavNodeKind,
  isConfigNodeKind,
  isPageLikeKind,
  isSystemRootDirectory,
  normalizeNavNode,
  normalizeNavRoot,
  normalizePageIdFromPath,
  normalizeRootChildPlacement,
} from './navigation'

// 命名空间 API
export { SparkPageConfig } from './namespace'

// ==================== 业务脚本 API 契约 ====================
// 框架无关的页面脚本上下文类型：PageRoute、ScriptContext
export type {
  PageRoute,
  ScriptContext,
  PageServiceInScript,
  ModuleContextInScript,
  ModuleContextItemInScript,
} from './script-context-types'
