/**
 * @packageDocumentation
 *
 * SPARK AI runtime package public entry point.
 *
 * The package exposes recursive module-registration contracts, the core
 * `AiRuntime` knowledge/translation facade, page-design module tools, and
 * component catalog projection helpers used by the SPARK configuration workflow.
 */

export {
  AiRuntime,
  AiInvocationProtocol,
  LlmParamsValidator,
  ParameterPayloadRegistry,
  addGuidedAiToolAction,
  createAiRuntimeToolCodec,
  createInitialAiToolActionSet,
} from './core'

export type {
  AiRuntimeApi,
  AiRuntimeAction,
  AiBusinessRegistration,
  AiBusinessRegistrationData,
  AiBusinessRegistrationStoreSnapshot,
  AiModuleRegistration,
  AiModuleRegistrationData,
  AiModuleRegistrationStoreModule,
  AiModuleRegistrationStoreSnapshot,
  AiModuleInstanceBinding,
  AiModuleInstanceParam,
  AiRuntimeAppendFunctionCallOptions,
  AiRuntimeAppendMessageOptions,
  AiRuntimeCompleteFunctionCallOptions,
  AiRuntimeActivePathSnapshot,
  AiRuntimeCreateFunctionResultMessageOptions,
  AiRuntimeFunctionContextParam,
  AiRuntimeFunctionCallFailure,
  AiRuntimeFunctionCallHistoryEntry,
  AiRuntimeFunctionCallHistoryStatus,
  AiRuntimeFunctionCallTranslation,
  AiRuntimeFunctionCallTranslationResult,
  AiRuntimeFunctionCallResult,
  AiRuntimeFunctionCallResultNormalizer,
  AiRuntimeFunctionCallRunInput,
  AiRuntimeFunctionCallRunner,
  AiRuntimeFunctionCallValidator,
  AiRuntimeFunctionExposure,
  AiRuntimeFunctionResultMessage,
  AiRuntimeHistoryEntry,
  AiRuntimeHistoryEntryBase,
  AiRuntimeHistoryEntryKind,
  AiRuntimeInstanceLifecycleSnapshot,
  AiRuntimeInstanceStatus,
  AiKnowledgeFunctionSummary,
  AiKnowledgeModuleSummary,
  AiKnowledgeProjection,
  AiKnowledgeScope,
  AiRuntimeFunctionId,
  AiRuntimeKnowledgeProjection,
  AiRuntimeMessageHistoryEntry,
  AiRuntimeMessageRole,
  AiRuntimeMessageSource,
  AiRuntimeModuleExposure,
  AiRuntimeModuleId,
  AiRuntimeModuleInstanceId,
  AiRuntimeModuleInstanceScope,
  AiRuntimeModulePath,
  AiRuntimeOptions,
  AiRuntimeProjectKnowledgeOptions,
  AiRuntimeExecuteFunctionCallOptions,
  AiRuntimeRecordFunctionCallRequestOptions,
  AiRuntimeSessionRecord,
  AiRuntimeSessionLifecycleSnapshot,
  AiRuntimeSessionStatus,
  AiRuntimeStartSessionOptions,
  AiRuntimeStartSessionResult,
  AiRuntimeStopSessionOptions,
  AiRuntimeStopSessionResult,
  AiRuntimeTranslateFunctionCallOptions,
  AiRuntimeToolCodec,
  AiRuntimeToolCodecOptions,
  AiRuntimeToolExposurePolicyOptions,
  AiRuntimeToolSpec,
  AiRegisteredModuleExecuteFunctionCallOptions,
  AiRegisteredModuleProjectKnowledgeOptions,
  AiRegisteredModuleStartSessionOptions,
  AiRegisteredModuleStopSessionOptions,
  AiRegisteredBusinessApi,
  AiRuntimeInstanceScope,
  AiFunctionRegistration,
  AiFunctionRegistrationData,
  AiFunctionRegistrationFailureMode,
  AiFunctionRegistrationStoreFunction,
  AiFunctionRegistrationUsageRule,
  FunctionFailureMode,
  FunctionExecutionContext,
  ModulePromptContext,
  ModulePromptProvider,
  ActionPathParts,
  ProtocolRole,
  ProtocolMessage,
  TokenUsage,
  StreamCallbacks,
  LlmJsonObject,
  LlmJsonPrimitive,
  LlmJsonSchema,
  LlmJsonSchemaObject,
  LlmJsonSchemaType,
  LlmJsonValue,
  LlmParameterSchemaRoot,
  LlmParamValidationIssue,
  LlmParamValidationResult,
  ParameterPayloadFailureMode,
  ParameterPayloadGuide,
  ParameterPayloadProvider,
  ParameterPayloadQueryFilter,
  ParameterPayloadSummary,
} from './core'

export {
  PAGE_DESIGN_MODULE_ID,
  PageDesignModule,
  SPARK_COMPONENT_PAYLOAD_DESCRIPTION,
  SPARK_COMPONENT_PAYLOAD_REF,
  guidePageDesignComponentPayload,
  queryPageDesignComponentPayloads,
  DATASET_CATALOG_ROWS,
  validateDatasetParams,
  PageDesignEditActionClassifier,
  PageDesignEditFlowPrompts,
  PageDesignEditRuntimePrompt,
  KNOWLEDGE_CATALOG_ROWS,
  validateKnowledgeParams,
  LIFECYCLE_CATALOG_ROWS,
  validateLifecycleParams,
  NODE_TREE_CATALOG_ROWS,
  validateNodeTreeParams,
  TEXT_MODEL_CATALOG_ROWS,
  validateTextModelParams,
} from './registrations/page-design'

export type {
  DatasetCrudToolFunctionFailureMode,
  DatasetCrudToolFunctionId,
  EditLifecycleFunctionFailureMode,
  EditLifecycleFunctionId,
  PageDesignAppendMessageOptions,
  PageDesignKnowledgeFunctionFailureMode,
  PageDesignKnowledgeFunctionId,
  PageDesignModuleContext,
  PageDesignExecuteFunctionCallOptions,
  PageDesignModuleId,
  PageDesignModuleOptions,
  PageDesignRuntimeContext,
  PageDesignStopSessionOptions,
  SparkNodeTreeToolFailureMode,
  SparkNodeTreeToolFunctionId,
  TextModelFunctionFailureMode,
  TextModelFunctionFileKey,
  TextModelFunctionId,
} from './registrations/page-design'

export {
  LEAVE_REQUEST_MODULE_ID,
  LeaveRequestModule,
  LeaveRequestService,
  assertLeaveRequestContext,
  createLeaveDraftId,
  isLeaveRequestServiceResult,
  leaveRequestServiceFailure,
} from './registrations/leave-request'

export type {
  LeaveRequestAppendMessageOptions,
  LeaveRequestDraftFields,
  LeaveRequestDraftState,
  LeaveRequestDraftStatus,
  LeaveRequestExecuteFunctionCallOptions,
  LeaveRequestRuntimeContext,
  LeaveRequestServiceContext,
  LeaveRequestServiceResult,
  LeaveRequestStopSessionOptions,
} from './registrations/leave-request'
