package com.spark.ai.service;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.spark.ai.security.AccessGuardService;
import jakarta.annotation.PostConstruct;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.EmptyResultDataAccessException;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.server.ResponseStatusException;

import javax.sql.DataSource;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.sql.Types;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import java.util.regex.Pattern;

/**
 * 元数据、物理表 DDL、已有表接管的统一服务。
 *
 * <p>该服务刻意保持 JdbcTemplate 风格，和现有 H2/JdbcTemplate 后端一致。对外暴露的
 * tableName 始终是逻辑表名，物理表名只存在于元数据和 SQL 白名单映射中。</p>
 */
@Service
public class DynamicDataModelService {

    public static final String ORIGIN_DYNAMIC_CREATED = "dynamic-created";
    public static final String ORIGIN_EXISTING_IMPORTED = "existing-imported";
    public static final String MANAGED_MODE_STRICT = "strict";

    private static final Pattern IDENTIFIER = Pattern.compile("[A-Za-z_][A-Za-z0-9_]*");
    private static final Set<String> SYSTEM_PHYSICAL_COLUMNS = Set.of("TENANT_ID", "PROJECT_ID");
    private static final Set<String> RESERVED_TABLES = Set.of(
            "DATA_MODEL_TABLE",
            "DATA_MODEL_COLUMN",
            "DATA_MODEL_VIEW",
            "DATA_BATCH_JOB",
            "DATA_BATCH_JOB_ITEM",
            "DATA_TRANSACTION_COMMIT"
    );

    private final JdbcTemplate jdbcTemplate;
    private final ObjectMapper objectMapper;
    private final DataSource dataSource;
    private final AccessGuardService accessGuardService;

    public DynamicDataModelService(JdbcTemplate jdbcTemplate, ObjectMapper objectMapper, DataSource dataSource) {
        this(jdbcTemplate, objectMapper, dataSource, null);
    }

    @Autowired
    public DynamicDataModelService(JdbcTemplate jdbcTemplate,
                                   ObjectMapper objectMapper,
                                   DataSource dataSource,
                                   AccessGuardService accessGuardService) {
        this.jdbcTemplate = jdbcTemplate;
        this.objectMapper = objectMapper;
        this.dataSource = dataSource;
        this.accessGuardService = accessGuardService;
    }

    @PostConstruct
    void ensureMetadataSchema() {
        if (isMySql()) {
            return;
        }
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS DATA_MODEL_TABLE (
                ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                TENANT_ID VARCHAR(255) NOT NULL,
                PROJECT_ID VARCHAR(255) NOT NULL,
                LOGICAL_TABLE_NAME VARCHAR(255) NOT NULL,
                ORIGIN VARCHAR(64) NOT NULL,
                MANAGED_MODE VARCHAR(64) NOT NULL,
                PHYSICAL_TABLE_NAME VARCHAR(255) NOT NULL,
                PRIMARY_KEY_FIELD VARCHAR(255) NOT NULL,
                RESOURCE_TYPE VARCHAR(64),
                RESOURCE_ID VARCHAR(255),
                BUSINESS_CATEGORY VARCHAR(64),
                SCHEMA_VERSION INT NOT NULL DEFAULT 1,
                DDL_HASH VARCHAR(128),
                STATUS VARCHAR(64) NOT NULL DEFAULT 'active',
                LAST_INTROSPECTED_AT TIMESTAMP,
                CREATED_AT TIMESTAMP NOT NULL,
                UPDATED_AT TIMESTAMP NOT NULL,
                UNIQUE (TENANT_ID, PROJECT_ID, LOGICAL_TABLE_NAME)
            )
            """);
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS DATA_MODEL_COLUMN (
                ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                TABLE_ID BIGINT NOT NULL,
                COLUMN_NAME VARCHAR(255) NOT NULL,
                PHYSICAL_COLUMN_NAME VARCHAR(255) NOT NULL,
                DATA_TYPE VARCHAR(64) NOT NULL,
                SQL_TYPE VARCHAR(255) NOT NULL,
                ORDINAL_POSITION INT NOT NULL,
                IS_PRIMARY_KEY BOOLEAN NOT NULL DEFAULT FALSE,
                IS_AUTO_INCREMENT BOOLEAN NOT NULL DEFAULT FALSE,
                IS_NULLABLE BOOLEAN NOT NULL DEFAULT TRUE,
                IS_REQUIRED BOOLEAN NOT NULL DEFAULT FALSE,
                MAX_LENGTH INT,
                NUMERIC_PRECISION INT,
                NUMERIC_SCALE INT,
                DEFAULT_VALUE VARCHAR(2000),
                LABEL VARCHAR(255),
                CREATED_AT TIMESTAMP NOT NULL,
                UPDATED_AT TIMESTAMP NOT NULL,
                UNIQUE (TABLE_ID, COLUMN_NAME)
            )
            """);
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS DATA_MODEL_VIEW (
                ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                TABLE_ID BIGINT NOT NULL,
                VIEW_ID VARCHAR(255) NOT NULL,
                VIEW_CONFIG CLOB NOT NULL,
                CREATED_AT TIMESTAMP NOT NULL,
                UPDATED_AT TIMESTAMP NOT NULL,
                UNIQUE (TABLE_ID, VIEW_ID)
            )
            """);
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS DATA_BATCH_JOB (
                JOB_ID VARCHAR(64) PRIMARY KEY,
                TENANT_ID VARCHAR(255) NOT NULL,
                PROJECT_ID VARCHAR(255) NOT NULL,
                REQUEST_ID VARCHAR(255),
                STATUS VARCHAR(64) NOT NULL,
                TOTAL_COUNT INT NOT NULL DEFAULT 0,
                COMPLETED_COUNT INT NOT NULL DEFAULT 0,
                SUCCESS_COUNT INT NOT NULL DEFAULT 0,
                FAILURE_COUNT INT NOT NULL DEFAULT 0,
                PAYLOAD CLOB,
                RESULT CLOB,
                ERROR_MESSAGE CLOB,
                CREATED_AT TIMESTAMP NOT NULL,
                UPDATED_AT TIMESTAMP NOT NULL,
                COMPLETED_AT TIMESTAMP
            )
            """);
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS DATA_BATCH_JOB_ITEM (
                ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                JOB_ID VARCHAR(64) NOT NULL,
                OPERATION_ID VARCHAR(255),
                TABLE_NAME VARCHAR(255) NOT NULL,
                OPERATION VARCHAR(64) NOT NULL,
                STATUS VARCHAR(64) NOT NULL,
                PAYLOAD CLOB,
                RESULT CLOB,
                ERROR_MESSAGE CLOB,
                CREATED_AT TIMESTAMP NOT NULL,
                UPDATED_AT TIMESTAMP NOT NULL
            )
            """);
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS DATA_TRANSACTION_COMMIT (
                TRANSACTION_ID VARCHAR(64) PRIMARY KEY,
                TENANT_ID VARCHAR(255) NOT NULL,
                PROJECT_ID VARCHAR(255) NOT NULL,
                REQUEST_ID VARCHAR(255) NOT NULL,
                REQUEST_HASH VARCHAR(128) NOT NULL,
                STATUS VARCHAR(64) NOT NULL,
                PAYLOAD CLOB,
                RESULT CLOB,
                CREATED_AT TIMESTAMP NOT NULL,
                UPDATED_AT TIMESTAMP NOT NULL,
                COMPLETED_AT TIMESTAMP,
                UNIQUE (TENANT_ID, PROJECT_ID, REQUEST_ID)
            )
            """);
        jdbcTemplate.execute("""
            CREATE INDEX IF NOT EXISTS IDX_DATA_MODEL_TABLE_SCOPE
            ON DATA_MODEL_TABLE (TENANT_ID, PROJECT_ID)
            """);
        jdbcTemplate.execute("""
            CREATE INDEX IF NOT EXISTS IDX_DATA_MODEL_COLUMN_TABLE
            ON DATA_MODEL_COLUMN (TABLE_ID, ORDINAL_POSITION)
            """);
        jdbcTemplate.execute("""
            CREATE INDEX IF NOT EXISTS IDX_DATA_BATCH_JOB_SCOPE
            ON DATA_BATCH_JOB (TENANT_ID, PROJECT_ID, CREATED_AT)
            """);
        jdbcTemplate.execute("""
            CREATE INDEX IF NOT EXISTS IDX_DATA_TRANSACTION_COMMIT_SCOPE
            ON DATA_TRANSACTION_COMMIT (TENANT_ID, PROJECT_ID, CREATED_AT)
            """);
    }

    private boolean isMySql() {
        try (Connection connection = dataSource.getConnection()) {
            String product = connection.getMetaData().getDatabaseProductName();
            return product != null && product.toLowerCase(Locale.ROOT).contains("mysql");
        } catch (Exception ignored) {
            return false;
        }
    }

    public List<Map<String, Object>> listTables(String tenantId, String projectId) {
        guardProject(tenantId, projectId);
        return jdbcTemplate.query("""
            SELECT * FROM DATA_MODEL_TABLE
            WHERE TENANT_ID = ? AND PROJECT_ID = ?
            ORDER BY LOGICAL_TABLE_NAME
            """, (rs, rowNum) -> toTableSummary(readTableInfo(rs)), tenantId, projectId);
    }

    public Map<String, Object> getTablePayload(String tenantId, String projectId, String logicalTableName) {
        guardProject(tenantId, projectId);
        TableDefinition definition = requireDefinition(tenantId, projectId, logicalTableName);
        return toFullTablePayload(definition);
    }

    @Transactional
    public Map<String, Object> createTable(String tenantId, String projectId, Map<String, Object> body) {
        guardProject(tenantId, projectId);
        String logicalName = readRequiredIdentifier(body.get("tableName"), "tableName");
        if (findTable(tenantId, projectId, logicalName) != null) {
            throw new ResponseStatusException(HttpStatus.CONFLICT, "逻辑表已存在: " + logicalName);
        }

        List<ColumnDraft> columns = readColumnDrafts(body.get("columns"));
        columns = ensurePrimaryKeyDraft(columns);
        String physicalName = readOptionalIdentifier(body.get("physicalTableName"));
        if (physicalName == null) {
            physicalName = generatePhysicalTableName(tenantId, projectId, logicalName);
        }
        assertIdentifier(physicalName, "physicalTableName");

        createPhysicalTable(physicalName, columns);
        return persistImportedOrCreatedTable(
                tenantId,
                projectId,
                logicalName,
                physicalName,
                ORIGIN_DYNAMIC_CREATED,
                body,
                scanPhysicalTable(physicalName),
                readViews(body.get("views"))
        );
    }

    @Transactional
    public Map<String, Object> updateTable(String tenantId, String projectId, String logicalTableName, Map<String, Object> body) {
        guardProject(tenantId, projectId);
        TableDefinition current = requireDefinition(tenantId, projectId, logicalTableName);
        boolean force = readBoolean(body.get("force"), false);
        List<Map<String, Object>> dangerous = new ArrayList<>();
        List<ColumnDraft> desired = body.containsKey("columns")
                ? ensurePrimaryKeyDraft(readColumnDrafts(body.get("columns")))
                : current.columns().stream().map(ColumnDraft::fromColumnInfo).toList();

        Map<String, ColumnInfo> existingByName = byColumnName(current.columns());
        Set<String> desiredNames = new LinkedHashSet<>();
        for (ColumnDraft draft : desired) {
            desiredNames.add(draft.columnName());
            ColumnInfo existing = existingByName.get(draft.columnName());
            if (existing == null) {
                jdbcTemplate.execute("ALTER TABLE " + q(current.table().physicalTableName())
                        + " ADD COLUMN " + q(draft.physicalColumnName()) + " " + draft.sqlType());
                continue;
            }
            if (!normalizeSqlType(existing.sqlType()).equals(normalizeSqlType(draft.sqlType()))) {
                dangerous.add(Map.of(
                        "kind", "type-change",
                        "column", draft.columnName(),
                        "from", existing.sqlType(),
                        "to", draft.sqlType()
                ));
            }
            if (existing.nullable() && !draft.nullable()) {
                dangerous.add(Map.of("kind", "nullable-tighten", "column", draft.columnName()));
            }
        }

        for (ColumnInfo existing : current.columns()) {
            if (!desiredNames.contains(existing.columnName())) {
                dangerous.add(Map.of("kind", "drop-column", "column", existing.columnName()));
            }
        }

        if (!dangerous.isEmpty() && !force) {
            throw new PreflightRequiredException(Map.of(
                    "message", "结构变更包含危险操作，需要 force=true",
                    "changes", dangerous
            ));
        }

        if (force) {
            for (ColumnDraft draft : desired) {
                ColumnInfo existing = existingByName.get(draft.columnName());
                if (existing == null) continue;
                if (!normalizeSqlType(existing.sqlType()).equals(normalizeSqlType(draft.sqlType()))) {
                    jdbcTemplate.execute("ALTER TABLE " + q(current.table().physicalTableName())
                            + " ALTER COLUMN " + q(existing.physicalColumnName()) + " " + draft.sqlType());
                }
                if (existing.nullable() && !draft.nullable()) {
                    jdbcTemplate.execute("ALTER TABLE " + q(current.table().physicalTableName())
                            + " ALTER COLUMN " + q(existing.physicalColumnName()) + " SET NOT NULL");
                }
            }
            for (ColumnInfo existing : current.columns()) {
                if (!desiredNames.contains(existing.columnName())) {
                    jdbcTemplate.execute("ALTER TABLE " + q(current.table().physicalTableName())
                            + " DROP COLUMN " + q(existing.physicalColumnName()));
                }
            }
        }

        IntrospectedTable introspected = scanPhysicalTable(current.table().physicalTableName());
        replaceColumnsFromIntrospection(current.table().id(), introspected);
        if (body.containsKey("views")) {
            replaceViews(current.table().id(), readViews(body.get("views")));
        }
        updateTableHashAndVersion(current.table().id(), hashTable(introspected), current.table().schemaVersion() + 1);
        return getTablePayload(tenantId, projectId, logicalTableName);
    }

    @Transactional
    public void deleteTable(String tenantId, String projectId, String logicalTableName, boolean forceDropPhysical) {
        guardProject(tenantId, projectId);
        TableDefinition definition = requireDefinition(tenantId, projectId, logicalTableName);
        jdbcTemplate.update("DELETE FROM DATA_MODEL_VIEW WHERE TABLE_ID = ?", definition.table().id());
        jdbcTemplate.update("DELETE FROM DATA_MODEL_COLUMN WHERE TABLE_ID = ?", definition.table().id());
        jdbcTemplate.update("DELETE FROM DATA_MODEL_TABLE WHERE ID = ?", definition.table().id());
        if (forceDropPhysical) {
            jdbcTemplate.execute("DROP TABLE IF EXISTS " + q(definition.table().physicalTableName()));
        }
    }

    public Map<String, Object> consistency(String tenantId, String projectId, String logicalTableName) {
        guardProject(tenantId, projectId);
        TableDefinition definition = requireDefinition(tenantId, projectId, logicalTableName);
        IntrospectedTable physical = scanPhysicalTable(definition.table().physicalTableName());
        List<Map<String, Object>> differences = diff(definition, physical);
        return Map.of(
                "consistent", differences.isEmpty(),
                "logicalTableName", definition.table().logicalTableName(),
                "physicalTableName", definition.table().physicalTableName(),
                "differences", differences,
                "ddlHash", hashTable(physical)
        );
    }

    @Transactional
    public Map<String, Object> reconcile(String tenantId, String projectId, String logicalTableName) {
        guardProject(tenantId, projectId);
        TableDefinition definition = requireDefinition(tenantId, projectId, logicalTableName);
        IntrospectedTable physical = scanPhysicalTable(definition.table().physicalTableName());
        replaceColumnsFromIntrospection(definition.table().id(), physical);
        updateTableHashAndVersion(definition.table().id(), hashTable(physical), definition.table().schemaVersion() + 1);
        return getTablePayload(tenantId, projectId, logicalTableName);
    }

    public List<Map<String, Object>> listPhysicalTables() {
        return listPhysicalTableNames().stream()
                .map(name -> describePhysicalTable(name, false))
                .toList();
    }

    public Map<String, Object> describePhysicalTable(String physicalTableName) {
        return describePhysicalTable(physicalTableName, true);
    }

    @Transactional
    public List<Map<String, Object>> importExistingTables(String tenantId, String projectId, Map<String, Object> body) {
        guardProject(tenantId, projectId);
        List<Map<String, Object>> tables = readImportTables(body);
        List<Map<String, Object>> imported = new ArrayList<>();
        for (Map<String, Object> tableRequest : tables) {
            String physicalName = readRequiredIdentifier(tableRequest.get("physicalTableName"), "physicalTableName");
            String logicalName = readOptionalIdentifier(tableRequest.get("logicalTableName"));
            if (logicalName == null) {
                logicalName = toLowerCamel(physicalName);
            }
            if (findTable(tenantId, projectId, logicalName) != null) {
                throw new ResponseStatusException(HttpStatus.CONFLICT, "逻辑表已存在: " + logicalName);
            }

            IntrospectedTable before = scanPhysicalTable(physicalName);
            ensureManagedPhysicalShape(tenantId, projectId, before);
            IntrospectedTable after = scanPhysicalTable(physicalName);
            Map<String, Object> requestBody = new LinkedHashMap<>(tableRequest);
            requestBody.put("resourceType", "database-table");
            requestBody.put("resourceId", logicalName);
            imported.add(persistImportedOrCreatedTable(
                    tenantId,
                    projectId,
                    logicalName,
                    physicalName,
                    ORIGIN_EXISTING_IMPORTED,
                    requestBody,
                    after,
                    readViews(tableRequest.get("views"))
            ));
        }
        return imported;
    }

    public TableDefinition requireDefinition(String tenantId, String projectId, String logicalTableName) {
        guardProject(tenantId, projectId);
        TableInfo table = findTable(tenantId, projectId, logicalTableName);
        if (table == null) {
            throw new NoSuchElementException("数据表元数据不存在: " + logicalTableName);
        }
        List<ColumnInfo> columns = listColumns(table.id());
        Map<String, Map<String, Object>> views = listViews(table.id());
        return new TableDefinition(table, columns, views);
    }

    private void guardProject(String tenantId, String projectId) {
        if (accessGuardService != null) {
            accessGuardService.requireProjectAccess(tenantId, projectId);
        }
    }

    public static String q(String identifier) {
        assertIdentifier(identifier, "identifier");
        return "\"" + identifier + "\"";
    }

    public static void assertIdentifier(String identifier, String fieldName) {
        if (identifier == null || !IDENTIFIER.matcher(identifier).matches()) {
            throw new IllegalArgumentException(fieldName + " 不是合法 SQL 标识符: " + identifier);
        }
    }

    private Map<String, Object> persistImportedOrCreatedTable(
            String tenantId,
            String projectId,
            String logicalName,
            String physicalName,
            String origin,
            Map<String, Object> requestBody,
            IntrospectedTable introspected,
            Map<String, Map<String, Object>> views
    ) {
        String primaryKey = introspected.primaryKeyColumns().stream()
                .findFirst()
                .map(DynamicDataModelService::toLowerCamel)
                .orElse("id");
        Timestamp now = Timestamp.from(Instant.now());
        String ddlHash = hashTable(introspected);
        jdbcTemplate.update("""
            INSERT INTO DATA_MODEL_TABLE (
                TENANT_ID, PROJECT_ID, LOGICAL_TABLE_NAME, ORIGIN, MANAGED_MODE,
                PHYSICAL_TABLE_NAME, PRIMARY_KEY_FIELD, RESOURCE_TYPE, RESOURCE_ID,
                BUSINESS_CATEGORY, SCHEMA_VERSION, DDL_HASH, STATUS,
                LAST_INTROSPECTED_AT, CREATED_AT, UPDATED_AT
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'active', ?, ?, ?)
            """,
                tenantId,
                projectId,
                logicalName,
                origin,
                MANAGED_MODE_STRICT,
                introspected.tableName(),
                primaryKey,
                stringOrDefault(requestBody.get("resourceType"), "database-table"),
                stringOrDefault(requestBody.get("resourceId"), logicalName),
                stringOrDefault(requestBody.get("businessCategory"), null),
                1,
                ddlHash,
                now,
                now,
                now
        );
        TableInfo table = Objects.requireNonNull(findTable(tenantId, projectId, logicalName));
        replaceColumnsFromIntrospection(table.id(), introspected);
        if (views.isEmpty()) {
            Map<String, Object> defaultView = new LinkedHashMap<>();
            defaultView.put("viewId", "default");
            defaultView.put("page", 1);
            defaultView.put("pageSize", 20);
            views = Map.of("default", defaultView);
        }
        replaceViews(table.id(), views);
        return getTablePayload(tenantId, projectId, logicalName);
    }

    private void createPhysicalTable(String physicalName, List<ColumnDraft> columns) {
        List<String> definitions = new ArrayList<>();
        definitions.add(q("TENANT_ID") + " VARCHAR(255) NOT NULL");
        definitions.add(q("PROJECT_ID") + " VARCHAR(255) NOT NULL");
        for (ColumnDraft column : columns) {
            String definition = q(column.physicalColumnName()) + " " + column.sqlType();
            if (column.autoIncrement()) {
                definition += " GENERATED BY DEFAULT AS IDENTITY";
            }
            if (!column.nullable() && !column.autoIncrement()) {
                definition += " NOT NULL";
            }
            if (column.primaryKey()) {
                definition += " PRIMARY KEY";
            }
            definitions.add(definition);
        }
        jdbcTemplate.execute("CREATE TABLE " + q(physicalName) + " (" + String.join(", ", definitions) + ")");
        jdbcTemplate.execute("CREATE INDEX IF NOT EXISTS " + q("IDX_" + physicalName + "_SCOPE")
                + " ON " + q(physicalName) + " (" + q("TENANT_ID") + ", " + q("PROJECT_ID") + ")");
    }

    private void ensureManagedPhysicalShape(String tenantId, String projectId, IntrospectedTable table) {
        boolean hasPrimaryKey = !table.primaryKeyColumns().isEmpty();
        if (!hasColumn(table, "TENANT_ID")) {
            jdbcTemplate.execute("ALTER TABLE " + q(table.tableName()) + " ADD COLUMN " + q("TENANT_ID") + " VARCHAR(255)");
            jdbcTemplate.update("UPDATE " + q(table.tableName()) + " SET " + q("TENANT_ID") + " = ? WHERE " + q("TENANT_ID") + " IS NULL", tenantId);
            tryAlter("ALTER TABLE " + q(table.tableName()) + " ALTER COLUMN " + q("TENANT_ID") + " SET NOT NULL");
        }
        if (!hasColumn(table, "PROJECT_ID")) {
            jdbcTemplate.execute("ALTER TABLE " + q(table.tableName()) + " ADD COLUMN " + q("PROJECT_ID") + " VARCHAR(255)");
            jdbcTemplate.update("UPDATE " + q(table.tableName()) + " SET " + q("PROJECT_ID") + " = ? WHERE " + q("PROJECT_ID") + " IS NULL", projectId);
            tryAlter("ALTER TABLE " + q(table.tableName()) + " ALTER COLUMN " + q("PROJECT_ID") + " SET NOT NULL");
        }
        if (!hasPrimaryKey) {
            jdbcTemplate.execute("ALTER TABLE " + q(table.tableName()) + " ADD COLUMN " + q("ID") + " BIGINT GENERATED BY DEFAULT AS IDENTITY");
            tryAlter("ALTER TABLE " + q(table.tableName()) + " ADD PRIMARY KEY (" + q("ID") + ")");
        }
        jdbcTemplate.execute("CREATE INDEX IF NOT EXISTS " + q("IDX_" + table.tableName() + "_SCOPE")
                + " ON " + q(table.tableName()) + " (" + q("TENANT_ID") + ", " + q("PROJECT_ID") + ")");
    }

    private void tryAlter(String sql) {
        try {
            jdbcTemplate.execute(sql);
        } catch (Exception ignored) {
            // H2 对部分历史表约束变更会拒绝；接管流程随后用 consistency 暴露差异。
        }
    }

    private IntrospectedTable scanPhysicalTable(String physicalTableName) {
        assertIdentifier(physicalTableName, "physicalTableName");
        try (Connection connection = dataSource.getConnection()) {
            DatabaseMetaData metaData = connection.getMetaData();
            String tableName = resolveActualTableName(metaData, physicalTableName);
            if (tableName == null) {
                throw new NoSuchElementException("物理表不存在: " + physicalTableName);
            }

            Set<String> primaryKeys = new LinkedHashSet<>();
            try (ResultSet pk = metaData.getPrimaryKeys(null, null, tableName)) {
                while (pk.next()) {
                    primaryKeys.add(pk.getString("COLUMN_NAME"));
                }
            }

            List<IntrospectedColumn> columns = new ArrayList<>();
            try (ResultSet rs = metaData.getColumns(null, null, tableName, null)) {
                while (rs.next()) {
                    String columnName = rs.getString("COLUMN_NAME");
                    int sqlTypeCode = rs.getInt("DATA_TYPE");
                    String typeName = rs.getString("TYPE_NAME");
                    int size = rs.getInt("COLUMN_SIZE");
                    int scale = rs.getInt("DECIMAL_DIGITS");
                    boolean nullable = rs.getInt("NULLABLE") != DatabaseMetaData.columnNoNulls;
                    String defaultValue = rs.getString("COLUMN_DEF");
                    int ordinalPosition = rs.getInt("ORDINAL_POSITION");
                    String autoIncrement = "";
                    try {
                        autoIncrement = rs.getString("IS_AUTOINCREMENT");
                    } catch (Exception ignored) {
                        // Driver optional column.
                    }
                    columns.add(new IntrospectedColumn(
                            columnName,
                            sqlTypeCode,
                            typeName,
                            size > 0 ? size : null,
                            scale >= 0 ? scale : null,
                            nullable,
                            defaultValue,
                            primaryKeys.contains(columnName),
                            "YES".equalsIgnoreCase(autoIncrement),
                            ordinalPosition
                    ));
                }
            }
            columns.sort(Comparator.comparingInt(IntrospectedColumn::ordinalPosition));
            return new IntrospectedTable(tableName, columns, primaryKeys);
        } catch (SQLException e) {
            throw new IllegalStateException("扫描数据库表失败: " + physicalTableName, e);
        }
    }

    private String resolveActualTableName(DatabaseMetaData metaData, String requestedName) throws SQLException {
        try (ResultSet rs = metaData.getTables(null, null, requestedName, new String[]{"TABLE"})) {
            if (rs.next()) return rs.getString("TABLE_NAME");
        }
        try (ResultSet rs = metaData.getTables(null, null, requestedName.toUpperCase(Locale.ROOT), new String[]{"TABLE"})) {
            if (rs.next()) return rs.getString("TABLE_NAME");
        }
        return null;
    }

    private List<String> listPhysicalTableNames() {
        try (Connection connection = dataSource.getConnection()) {
            DatabaseMetaData metaData = connection.getMetaData();
            List<String> names = new ArrayList<>();
            try (ResultSet rs = metaData.getTables(null, null, null, new String[]{"TABLE"})) {
                while (rs.next()) {
                    String schema = rs.getString("TABLE_SCHEM");
                    String name = rs.getString("TABLE_NAME");
                    if (isImportableTable(schema, name)) {
                        names.add(name);
                    }
                }
            }
            names.sort(String::compareToIgnoreCase);
            return names;
        } catch (SQLException e) {
            throw new IllegalStateException("扫描数据库表失败", e);
        }
    }

    private boolean isImportableTable(String schema, String tableName) {
        if (tableName == null) return false;
        String upperSchema = schema == null ? "" : schema.toUpperCase(Locale.ROOT);
        String upper = tableName.toUpperCase(Locale.ROOT);
        if (upperSchema.contains("INFORMATION_SCHEMA")) return false;
        if (upper.startsWith("SYS")) return false;
        return !RESERVED_TABLES.contains(upper);
    }

    private Map<String, Object> describePhysicalTable(String physicalTableName, boolean includeColumns) {
        IntrospectedTable table = scanPhysicalTable(physicalTableName);
        Map<String, Object> payload = new LinkedHashMap<>();
        payload.put("physicalTableName", table.tableName());
        payload.put("primaryKeyColumns", table.primaryKeyColumns());
        payload.put("managed", isManagedPhysicalTable(table.tableName()));
        if (includeColumns) {
            payload.put("columns", table.columns().stream().map(this::toIntrospectionPayload).toList());
        }
        return payload;
    }

    private boolean isManagedPhysicalTable(String physicalTableName) {
        Integer count = jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM DATA_MODEL_TABLE WHERE PHYSICAL_TABLE_NAME = ?",
                Integer.class,
                physicalTableName
        );
        return count != null && count > 0;
    }

    private void replaceColumnsFromIntrospection(long tableId, IntrospectedTable table) {
        jdbcTemplate.update("DELETE FROM DATA_MODEL_COLUMN WHERE TABLE_ID = ?", tableId);
        Timestamp now = Timestamp.from(Instant.now());
        int ordinal = 0;
        for (IntrospectedColumn physical : table.columns()) {
            if (SYSTEM_PHYSICAL_COLUMNS.contains(physical.columnName().toUpperCase(Locale.ROOT))) {
                continue;
            }
            String logical = toLowerCamel(physical.columnName());
            jdbcTemplate.update("""
                INSERT INTO DATA_MODEL_COLUMN (
                    TABLE_ID, COLUMN_NAME, PHYSICAL_COLUMN_NAME, DATA_TYPE, SQL_TYPE,
                    ORDINAL_POSITION, IS_PRIMARY_KEY, IS_AUTO_INCREMENT, IS_NULLABLE,
                    IS_REQUIRED, MAX_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE,
                    DEFAULT_VALUE, LABEL, CREATED_AT, UPDATED_AT
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                    tableId,
                    logical,
                    physical.columnName(),
                    dataTypeFromSqlType(physical),
                    sqlTypeFromIntrospection(physical),
                    ordinal++,
                    physical.primaryKey(),
                    physical.autoIncrement(),
                    physical.nullable(),
                    !physical.nullable(),
                    physical.size(),
                    physical.size(),
                    physical.scale(),
                    physical.defaultValue(),
                    humanizeLabel(logical),
                    now,
                    now
            );
        }
    }

    private void replaceViews(long tableId, Map<String, Map<String, Object>> views) {
        jdbcTemplate.update("DELETE FROM DATA_MODEL_VIEW WHERE TABLE_ID = ?", tableId);
        Timestamp now = Timestamp.from(Instant.now());
        for (Map.Entry<String, Map<String, Object>> entry : views.entrySet()) {
            Map<String, Object> config = new LinkedHashMap<>(entry.getValue());
            config.putIfAbsent("viewId", entry.getKey());
            if ("default".equals(entry.getKey())) {
                config.putIfAbsent("page", 1);
                config.putIfAbsent("pageSize", 20);
            }
            jdbcTemplate.update("""
                INSERT INTO DATA_MODEL_VIEW (TABLE_ID, VIEW_ID, VIEW_CONFIG, CREATED_AT, UPDATED_AT)
                VALUES (?, ?, ?, ?, ?)
                """,
                    tableId,
                    entry.getKey(),
                    writeJson(config),
                    now,
                    now
            );
        }
    }

    private void updateTableHashAndVersion(long tableId, String ddlHash, int schemaVersion) {
        Timestamp now = Timestamp.from(Instant.now());
        jdbcTemplate.update("""
            UPDATE DATA_MODEL_TABLE
            SET DDL_HASH = ?, SCHEMA_VERSION = ?, LAST_INTROSPECTED_AT = ?, UPDATED_AT = ?
            WHERE ID = ?
            """, ddlHash, schemaVersion, now, now, tableId);
    }

    private TableInfo findTable(String tenantId, String projectId, String logicalTableName) {
        try {
            return jdbcTemplate.queryForObject("""
                SELECT * FROM DATA_MODEL_TABLE
                WHERE TENANT_ID = ? AND PROJECT_ID = ? AND LOGICAL_TABLE_NAME = ?
                """, (rs, rowNum) -> readTableInfo(rs), tenantId, projectId, logicalTableName);
        } catch (EmptyResultDataAccessException e) {
            return null;
        }
    }

    private List<ColumnInfo> listColumns(long tableId) {
        return jdbcTemplate.query("""
            SELECT * FROM DATA_MODEL_COLUMN
            WHERE TABLE_ID = ?
            ORDER BY ORDINAL_POSITION, ID
            """, (rs, rowNum) -> new ColumnInfo(
                rs.getLong("ID"),
                tableId,
                rs.getString("COLUMN_NAME"),
                rs.getString("PHYSICAL_COLUMN_NAME"),
                rs.getString("DATA_TYPE"),
                rs.getString("SQL_TYPE"),
                rs.getInt("ORDINAL_POSITION"),
                rs.getBoolean("IS_PRIMARY_KEY"),
                rs.getBoolean("IS_AUTO_INCREMENT"),
                rs.getBoolean("IS_NULLABLE"),
                rs.getBoolean("IS_REQUIRED"),
                readNullableInt(rs.getObject("MAX_LENGTH")),
                readNullableInt(rs.getObject("NUMERIC_PRECISION")),
                readNullableInt(rs.getObject("NUMERIC_SCALE")),
                rs.getString("DEFAULT_VALUE"),
                rs.getString("LABEL")
        ), tableId);
    }

    private Map<String, Map<String, Object>> listViews(long tableId) {
        Map<String, Map<String, Object>> result = new LinkedHashMap<>();
        jdbcTemplate.query("""
            SELECT VIEW_ID, VIEW_CONFIG FROM DATA_MODEL_VIEW
            WHERE TABLE_ID = ?
            ORDER BY VIEW_ID
            """, rs -> {
            result.put(rs.getString("VIEW_ID"), readJsonMap(rs.getString("VIEW_CONFIG")));
        }, tableId);
        return result;
    }

    private TableInfo readTableInfo(ResultSet rs) throws SQLException {
        return new TableInfo(
                rs.getLong("ID"),
                rs.getString("TENANT_ID"),
                rs.getString("PROJECT_ID"),
                rs.getString("LOGICAL_TABLE_NAME"),
                rs.getString("ORIGIN"),
                rs.getString("MANAGED_MODE"),
                rs.getString("PHYSICAL_TABLE_NAME"),
                rs.getString("PRIMARY_KEY_FIELD"),
                rs.getString("RESOURCE_TYPE"),
                rs.getString("RESOURCE_ID"),
                rs.getString("BUSINESS_CATEGORY"),
                rs.getInt("SCHEMA_VERSION"),
                rs.getString("DDL_HASH"),
                rs.getString("STATUS")
        );
    }

    private List<Map<String, Object>> diff(TableDefinition definition, IntrospectedTable physical) {
        Map<String, IntrospectedColumn> physicalByLogical = new LinkedHashMap<>();
        for (IntrospectedColumn column : physical.columns()) {
            physicalByLogical.put(toLowerCamel(column.columnName()), column);
        }
        List<Map<String, Object>> differences = new ArrayList<>();
        for (ColumnInfo column : definition.columns()) {
            IntrospectedColumn physicalColumn = physicalByLogical.get(column.columnName());
            if (physicalColumn == null) {
                differences.add(Map.of("kind", "missing-physical-column", "column", column.columnName()));
                continue;
            }
            String physicalSqlType = normalizeSqlType(sqlTypeFromIntrospection(physicalColumn));
            if (!physicalSqlType.equals(normalizeSqlType(column.sqlType()))) {
                differences.add(Map.of(
                        "kind", "type-mismatch",
                        "column", column.columnName(),
                        "metadata", column.sqlType(),
                        "physical", sqlTypeFromIntrospection(physicalColumn)
                ));
            }
        }
        Set<String> metadataNames = new LinkedHashSet<>(definition.columns().stream().map(ColumnInfo::columnName).toList());
        for (IntrospectedColumn column : physical.columns()) {
            if (SYSTEM_PHYSICAL_COLUMNS.contains(column.columnName().toUpperCase(Locale.ROOT))) continue;
            String logical = toLowerCamel(column.columnName());
            if (!metadataNames.contains(logical)) {
                differences.add(Map.of("kind", "missing-metadata-column", "column", logical));
            }
        }
        return differences;
    }

    private Map<String, Object> toFullTablePayload(TableDefinition definition) {
        Map<String, Object> payload = toTableSummary(definition.table());
        payload.put("columns", definition.columns().stream().map(this::toColumnPayload).toList());
        payload.put("views", definition.views());
        return payload;
    }

    private Map<String, Object> toTableSummary(TableInfo table) {
        Map<String, Object> payload = new LinkedHashMap<>();
        payload.put("id", table.id());
        payload.put("tenantId", table.tenantId());
        payload.put("projectId", table.projectId());
        payload.put("tableName", table.logicalTableName());
        payload.put("origin", table.origin());
        payload.put("managedMode", table.managedMode());
        payload.put("physicalTableName", table.physicalTableName());
        payload.put("primaryKeyField", table.primaryKeyField());
        payload.put("resourceType", table.resourceType());
        payload.put("resourceId", table.resourceId());
        payload.put("businessCategory", table.businessCategory());
        payload.put("schemaVersion", table.schemaVersion());
        payload.put("ddlHash", table.ddlHash());
        payload.put("status", table.status());
        return payload;
    }

    private Map<String, Object> toColumnPayload(ColumnInfo column) {
        Map<String, Object> payload = new LinkedHashMap<>();
        payload.put("id", column.id());
        payload.put("name", column.columnName());
        payload.put("physicalColumnName", column.physicalColumnName());
        payload.put("type", column.dataType());
        payload.put("sqlType", column.sqlType());
        payload.put("primaryKey", column.primaryKey());
        payload.put("autoIncrement", column.autoIncrement());
        payload.put("nullable", column.nullable());
        payload.put("required", column.required());
        payload.put("maxLength", column.maxLength());
        payload.put("numericPrecision", column.numericPrecision());
        payload.put("numericScale", column.numericScale());
        payload.put("defaultValue", column.defaultValue());
        payload.put("label", column.label());
        return payload;
    }

    private Map<String, Object> toIntrospectionPayload(IntrospectedColumn column) {
        Map<String, Object> payload = new LinkedHashMap<>();
        payload.put("name", toLowerCamel(column.columnName()));
        payload.put("physicalColumnName", column.columnName());
        payload.put("type", dataTypeFromSqlType(column));
        payload.put("sqlType", sqlTypeFromIntrospection(column));
        payload.put("primaryKey", column.primaryKey());
        payload.put("autoIncrement", column.autoIncrement());
        payload.put("nullable", column.nullable());
        payload.put("ordinalPosition", column.ordinalPosition());
        payload.put("size", column.size());
        payload.put("scale", column.scale());
        payload.put("defaultValue", column.defaultValue());
        return payload;
    }

    private List<Map<String, Object>> readImportTables(Map<String, Object> body) {
        Object tablesValue = body == null ? null : body.get("tables");
        if (!(tablesValue instanceof List<?> rawList)) {
            throw new IllegalArgumentException("tables 必须是数组");
        }
        List<Map<String, Object>> tables = new ArrayList<>();
        for (Object item : rawList) {
            if (!(item instanceof Map<?, ?> rawMap)) {
                throw new IllegalArgumentException("tables 内每项必须是对象");
            }
            tables.add(toStringKeyMap(rawMap));
        }
        return tables;
    }

    private List<ColumnDraft> readColumnDrafts(Object value) {
        if (!(value instanceof List<?> rawList)) {
            throw new IllegalArgumentException("columns 必须是数组");
        }
        List<ColumnDraft> columns = new ArrayList<>();
        for (Object item : rawList) {
            if (!(item instanceof Map<?, ?> rawColumn)) {
                throw new IllegalArgumentException("columns 内每项必须是对象");
            }
            Map<String, Object> column = toStringKeyMap(rawColumn);
            String logicalName = readRequiredIdentifier(column.get("name"), "columns.name");
            String physicalName = readOptionalIdentifier(column.get("physicalColumnName"));
            if (physicalName == null) {
                physicalName = toUpperSnake(logicalName);
            }
            String dataType = stringOrDefault(column.get("type"), "string");
            Integer maxLength = readNullableInt(column.get("maxLength"));
            Integer precision = readNullableInt(column.get("numericPrecision"));
            Integer scale = readNullableInt(column.get("numericScale"));
            boolean primaryKey = readBoolean(column.get("primaryKey"), "id".equals(logicalName));
            boolean autoIncrement = readBoolean(column.get("autoIncrement"), primaryKey && isNumericDataType(dataType));
            boolean nullable = !primaryKey && !readBoolean(column.get("required"), false) && readBoolean(column.get("nullable"), true);
            String sqlType = stringOrDefault(column.get("sqlType"), sqlTypeFromDataType(dataType, maxLength, precision, scale));
            columns.add(new ColumnDraft(
                    logicalName,
                    physicalName,
                    dataType,
                    sqlType,
                    primaryKey,
                    autoIncrement,
                    nullable,
                    maxLength,
                    precision,
                    scale,
                    stringOrDefault(column.get("label"), humanizeLabel(logicalName))
            ));
        }
        return columns;
    }

    private List<ColumnDraft> ensurePrimaryKeyDraft(List<ColumnDraft> columns) {
        boolean hasPrimaryKey = columns.stream().anyMatch(ColumnDraft::primaryKey);
        if (hasPrimaryKey) return columns;
        List<ColumnDraft> result = new ArrayList<>();
        result.add(new ColumnDraft("id", "ID", "number", "BIGINT", true, true, false, null, null, null, "ID"));
        result.addAll(columns);
        return result;
    }

    private Map<String, Map<String, Object>> readViews(Object value) {
        if (value == null) return Map.of();
        if (!(value instanceof Map<?, ?> rawViews)) {
            throw new IllegalArgumentException("views 必须是对象");
        }
        Map<String, Map<String, Object>> views = new LinkedHashMap<>();
        rawViews.forEach((key, view) -> {
            if (!(view instanceof Map<?, ?> rawView)) {
                throw new IllegalArgumentException("views." + key + " 必须是对象");
            }
            views.put(String.valueOf(key), toStringKeyMap(rawView));
        });
        return views;
    }

    private Map<String, ColumnInfo> byColumnName(Collection<ColumnInfo> columns) {
        Map<String, ColumnInfo> result = new LinkedHashMap<>();
        for (ColumnInfo column : columns) {
            result.put(column.columnName(), column);
        }
        return result;
    }

    private static boolean hasColumn(IntrospectedTable table, String columnName) {
        return table.columns().stream().anyMatch(column -> column.columnName().equalsIgnoreCase(columnName));
    }

    private static String readRequiredIdentifier(Object value, String fieldName) {
        if (!(value instanceof String text) || text.isBlank()) {
            throw new IllegalArgumentException(fieldName + " 不能为空");
        }
        String trimmed = text.trim();
        assertIdentifier(trimmed, fieldName);
        return trimmed;
    }

    private static String readOptionalIdentifier(Object value) {
        if (value == null) return null;
        if (!(value instanceof String text) || text.isBlank()) return null;
        String trimmed = text.trim();
        assertIdentifier(trimmed, "identifier");
        return trimmed;
    }

    private static String stringOrDefault(Object value, String defaultValue) {
        if (value == null) return defaultValue;
        String text = String.valueOf(value).trim();
        return text.isEmpty() ? defaultValue : text;
    }

    private static boolean readBoolean(Object value, boolean defaultValue) {
        if (value == null) return defaultValue;
        if (value instanceof Boolean bool) return bool;
        if (value instanceof String text) return Boolean.parseBoolean(text);
        return defaultValue;
    }

    private static Integer readNullableInt(Object value) {
        if (value == null) return null;
        if (value instanceof Number number) return number.intValue();
        if (value instanceof String text && !text.isBlank()) return Integer.parseInt(text.trim());
        return null;
    }

    private static Map<String, Object> toStringKeyMap(Map<?, ?> raw) {
        Map<String, Object> result = new LinkedHashMap<>();
        raw.forEach((key, value) -> result.put(String.valueOf(key), value));
        return result;
    }

    private String writeJson(Object value) {
        try {
            return objectMapper.writeValueAsString(value);
        } catch (Exception e) {
            throw new IllegalArgumentException("JSON 序列化失败", e);
        }
    }

    private Map<String, Object> readJsonMap(String json) {
        if (json == null || json.isBlank()) return new LinkedHashMap<>();
        try {
            @SuppressWarnings("unchecked")
            Map<String, Object> result = objectMapper.readValue(json, LinkedHashMap.class);
            return result;
        } catch (Exception e) {
            throw new IllegalStateException("读取元数据 JSON 失败", e);
        }
    }

    private static String generatePhysicalTableName(String tenantId, String projectId, String logicalName) {
        String seed = tenantId + ":" + projectId + ":" + logicalName;
        return "APP_DATA_" + shortHash(seed).toUpperCase(Locale.ROOT);
    }

    private static String hashTable(IntrospectedTable table) {
        StringBuilder builder = new StringBuilder(table.tableName()).append('|');
        for (IntrospectedColumn column : table.columns()) {
            builder.append(column.columnName()).append(':')
                    .append(column.typeName()).append(':')
                    .append(column.size()).append(':')
                    .append(column.scale()).append(':')
                    .append(column.nullable()).append(':')
                    .append(column.primaryKey()).append(';');
        }
        return sha256(builder.toString());
    }

    private static String shortHash(String text) {
        return sha256(text).substring(0, 16);
    }

    private static String sha256(String text) {
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            byte[] bytes = digest.digest(text.getBytes(StandardCharsets.UTF_8));
            StringBuilder builder = new StringBuilder();
            for (byte b : bytes) {
                builder.append(String.format("%02x", b));
            }
            return builder.toString();
        } catch (Exception e) {
            throw new IllegalStateException("SHA-256 不可用", e);
        }
    }

    private static String toUpperSnake(String logicalName) {
        StringBuilder builder = new StringBuilder();
        for (int i = 0; i < logicalName.length(); i++) {
            char c = logicalName.charAt(i);
            if (Character.isUpperCase(c) && i > 0) {
                builder.append('_');
            }
            builder.append(Character.toUpperCase(c));
        }
        return builder.toString().replaceAll("[^A-Z0-9_]", "_");
    }

    public static String toLowerCamel(String physicalName) {
        String[] parts = physicalName.toLowerCase(Locale.ROOT).split("_+");
        if (parts.length == 0) return physicalName.toLowerCase(Locale.ROOT);
        StringBuilder builder = new StringBuilder(parts[0]);
        for (int i = 1; i < parts.length; i++) {
            if (parts[i].isEmpty()) continue;
            builder.append(Character.toUpperCase(parts[i].charAt(0))).append(parts[i].substring(1));
        }
        return builder.toString();
    }

    private static String humanizeLabel(String logicalName) {
        if ("id".equals(logicalName)) return "ID";
        String withSpaces = logicalName.replaceAll("([a-z])([A-Z])", "$1 $2");
        return Character.toUpperCase(withSpaces.charAt(0)) + withSpaces.substring(1);
    }

    private static String sqlTypeFromDataType(String dataType, Integer maxLength, Integer precision, Integer scale) {
        return switch (dataType.toLowerCase(Locale.ROOT)) {
            case "int", "integer" -> "INT";
            case "number", "long", "bigint" -> "BIGINT";
            case "decimal" -> "DECIMAL(" + (precision != null ? precision : 18) + "," + (scale != null ? scale : 2) + ")";
            case "float", "double" -> "DOUBLE";
            case "boolean", "bool" -> "BOOLEAN";
            case "date" -> "DATE";
            case "datetime", "timestamp" -> "TIMESTAMP";
            case "time" -> "TIME";
            case "text", "object", "array" -> "CLOB";
            default -> "VARCHAR(" + (maxLength != null ? maxLength : 255) + ")";
        };
    }

    private static boolean isNumericDataType(String dataType) {
        String normalized = dataType.toLowerCase(Locale.ROOT);
        return Set.of("int", "integer", "number", "long", "bigint").contains(normalized);
    }

    private static String dataTypeFromSqlType(IntrospectedColumn column) {
        return switch (column.sqlTypeCode()) {
            case Types.INTEGER, Types.SMALLINT, Types.TINYINT -> "integer";
            case Types.BIGINT, Types.NUMERIC, Types.DECIMAL, Types.DOUBLE, Types.FLOAT, Types.REAL -> "number";
            case Types.BOOLEAN, Types.BIT -> "boolean";
            case Types.DATE -> "date";
            case Types.TIMESTAMP, Types.TIMESTAMP_WITH_TIMEZONE -> "datetime";
            case Types.TIME, Types.TIME_WITH_TIMEZONE -> "time";
            case Types.CLOB, Types.LONGVARCHAR, Types.LONGNVARCHAR -> "text";
            default -> "string";
        };
    }

    private static String sqlTypeFromIntrospection(IntrospectedColumn column) {
        String type = column.typeName() == null ? "VARCHAR" : column.typeName().toUpperCase(Locale.ROOT);
        if ((type.contains("CHAR") || type.contains("VARCHAR")) && column.size() != null && column.size() > 0) {
            return "VARCHAR(" + column.size() + ")";
        }
        if ((type.contains("DECIMAL") || type.contains("NUMERIC")) && column.size() != null && column.scale() != null) {
            return "DECIMAL(" + column.size() + "," + column.scale() + ")";
        }
        if (type.contains("IDENTITY")) return "BIGINT";
        return type.replace(" CHARACTER VARYING", "VARCHAR");
    }

    private static String normalizeSqlType(String sqlType) {
        return sqlType == null ? "" : sqlType.toUpperCase(Locale.ROOT).replaceAll("\\s+", " ").trim();
    }

    public record TableDefinition(TableInfo table, List<ColumnInfo> columns, Map<String, Map<String, Object>> views) {}

    public record TableInfo(
            long id,
            String tenantId,
            String projectId,
            String logicalTableName,
            String origin,
            String managedMode,
            String physicalTableName,
            String primaryKeyField,
            String resourceType,
            String resourceId,
            String businessCategory,
            int schemaVersion,
            String ddlHash,
            String status
    ) {}

    public record ColumnInfo(
            long id,
            long tableId,
            String columnName,
            String physicalColumnName,
            String dataType,
            String sqlType,
            int ordinalPosition,
            boolean primaryKey,
            boolean autoIncrement,
            boolean nullable,
            boolean required,
            Integer maxLength,
            Integer numericPrecision,
            Integer numericScale,
            String defaultValue,
            String label
    ) {}

    private record ColumnDraft(
            String columnName,
            String physicalColumnName,
            String dataType,
            String sqlType,
            boolean primaryKey,
            boolean autoIncrement,
            boolean nullable,
            Integer maxLength,
            Integer numericPrecision,
            Integer numericScale,
            String label
    ) {
        static ColumnDraft fromColumnInfo(ColumnInfo column) {
            return new ColumnDraft(
                    column.columnName(),
                    column.physicalColumnName(),
                    column.dataType(),
                    column.sqlType(),
                    column.primaryKey(),
                    column.autoIncrement(),
                    column.nullable(),
                    column.maxLength(),
                    column.numericPrecision(),
                    column.numericScale(),
                    column.label()
            );
        }
    }

    public record IntrospectedTable(String tableName, List<IntrospectedColumn> columns, Set<String> primaryKeyColumns) {}

    public record IntrospectedColumn(
            String columnName,
            int sqlTypeCode,
            String typeName,
            Integer size,
            Integer scale,
            boolean nullable,
            String defaultValue,
            boolean primaryKey,
            boolean autoIncrement,
            int ordinalPosition
    ) {}

    public static class PreflightRequiredException extends RuntimeException {
        private final Map<String, Object> report;

        public PreflightRequiredException(Map<String, Object> report) {
            super(String.valueOf(report.getOrDefault("message", "preflight required")));
            this.report = report;
        }

        public Map<String, Object> report() {
            return report;
        }
    }
}
