package com.spark.ai.service;

import com.spark.ai.crud.FilterExpressionSqlBuilder;
import com.spark.ai.crud.FilterExpressionSqlBuilder.SqlFragment;
import com.spark.ai.security.AccessGuardService;
import jakarta.annotation.PostConstruct;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.support.GeneratedKeyHolder;
import org.springframework.jdbc.support.KeyHolder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;

/**
 * 独立远端过滤用例资源服务。
 *
 * <p>用途：作为统一 CRUD + POST query.filter AST 的最小后端落点，避免污染导航等现有业务表。
 */
@Service
public class FilterExpressionCaseService {

    private static final Map<String, String> QUERY_FIELD_SQL = Map.ofEntries(
            Map.entry("id", "ID"),
            Map.entry("title", "TITLE"),
            Map.entry("status", "STATUS"),
            Map.entry("priority", "PRIORITY"),
            Map.entry("amount", "AMOUNT"),
            Map.entry("threshold", "THRESHOLD"),
            Map.entry("amountDelta", "(AMOUNT - THRESHOLD)"),
            Map.entry("category", "CATEGORY"),
            Map.entry("createdAt", "CREATED_AT"),
            Map.entry("updatedAt", "UPDATED_AT")
    );

    private static final String ROW_PROJECTION_SQL = """
        ID,
        TITLE,
        STATUS,
        PRIORITY,
        AMOUNT,
        THRESHOLD,
        (AMOUNT - THRESHOLD) AS AMOUNT_DELTA,
        CATEGORY,
        CREATED_AT,
        UPDATED_AT
        """;

    private static final String BASE_FROM_SQL = """
        FROM FILTER_EXPRESSION_CASE
        WHERE TENANT_ID = ? AND PROJECT_ID = ?
        """;

    private static final String CREATE_TABLE_SQL = """
        CREATE TABLE IF NOT EXISTS FILTER_EXPRESSION_CASE (
            ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            TENANT_ID VARCHAR(255) NOT NULL,
            PROJECT_ID VARCHAR(255) NOT NULL,
            TITLE VARCHAR(255) NOT NULL,
            STATUS VARCHAR(64) NOT NULL,
            PRIORITY INT NOT NULL,
            AMOUNT DECIMAL(18,2) NOT NULL,
            THRESHOLD DECIMAL(18,2) NOT NULL,
            CATEGORY VARCHAR(64),
            CREATED_AT TIMESTAMP NOT NULL,
            UPDATED_AT TIMESTAMP NOT NULL
        )
        """;

    private static final String CREATE_SCOPE_INDEX_SQL = """
        CREATE INDEX IF NOT EXISTS IDX_FILTER_EXPR_CASE_SCOPE
        ON FILTER_EXPRESSION_CASE (TENANT_ID, PROJECT_ID)
        """;

    private static final String SELECT_ALL_SQL = """
        SELECT %s
        %s
        """;

    private static final String SELECT_ONE_SQL = """
        SELECT %s
        %s
          AND ID = ?
        """;

    private static final String COUNT_SQL = """
        SELECT COUNT(*)
        %s
        """;

    private static final String INSERT_SQL = """
        INSERT INTO FILTER_EXPRESSION_CASE (
            TENANT_ID, PROJECT_ID, TITLE, STATUS, PRIORITY, AMOUNT, THRESHOLD, CATEGORY, CREATED_AT, UPDATED_AT
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """;

    private static final String UPDATE_SQL = """
        UPDATE FILTER_EXPRESSION_CASE
        SET TITLE = ?, STATUS = ?, PRIORITY = ?, AMOUNT = ?, THRESHOLD = ?, CATEGORY = ?, UPDATED_AT = ?
        WHERE TENANT_ID = ? AND PROJECT_ID = ? AND ID = ?
        """;

    private static final String DELETE_SQL = """
        DELETE FROM FILTER_EXPRESSION_CASE
        WHERE TENANT_ID = ? AND PROJECT_ID = ? AND ID = ?
        """;

    private final JdbcTemplate jdbcTemplate;
    private final AccessGuardService accessGuardService;
    private final FilterExpressionSqlBuilder filterExpressionSqlBuilder = new FilterExpressionSqlBuilder(QUERY_FIELD_SQL);

    public FilterExpressionCaseService(JdbcTemplate jdbcTemplate) {
        this(jdbcTemplate, null);
    }

    @Autowired
    public FilterExpressionCaseService(JdbcTemplate jdbcTemplate, AccessGuardService accessGuardService) {
        this.jdbcTemplate = jdbcTemplate;
        this.accessGuardService = accessGuardService;
    }

    @PostConstruct
    void ensureSchema() {
        if (isMySql()) {
            return;
        }
        jdbcTemplate.execute(CREATE_TABLE_SQL);
        jdbcTemplate.execute(CREATE_SCOPE_INDEX_SQL);
    }

    private boolean isMySql() {
        try (var connection = jdbcTemplate.getDataSource().getConnection()) {
            String product = connection.getMetaData().getDatabaseProductName();
            return product != null && product.toLowerCase().contains("mysql");
        } catch (Exception ignored) {
            return false;
        }
    }

    @Transactional
    public Map<String, Object> createCase(String tenantId, String projectId, Map<String, Object> body) {
        guardProject(tenantId, projectId);
        Map<String, Object> normalized = normalizePayload(body, true);
        Instant now = Instant.now();

        KeyHolder keyHolder = new GeneratedKeyHolder();
        jdbcTemplate.update(connection -> {
            PreparedStatement statement = connection.prepareStatement(INSERT_SQL, Statement.RETURN_GENERATED_KEYS);
            statement.setString(1, tenantId);
            statement.setString(2, projectId);
            statement.setString(3, (String) normalized.get("title"));
            statement.setString(4, (String) normalized.get("status"));
            statement.setInt(5, (Integer) normalized.get("priority"));
            statement.setBigDecimal(6, (BigDecimal) normalized.get("amount"));
            statement.setBigDecimal(7, (BigDecimal) normalized.get("threshold"));
            statement.setString(8, (String) normalized.get("category"));
            statement.setTimestamp(9, Timestamp.from(now));
            statement.setTimestamp(10, Timestamp.from(now));
            return statement;
        }, keyHolder);

        Number key = keyHolder.getKey();
        if (key == null) {
            throw new IllegalStateException("创建过滤用例失败：未返回主键");
        }
        return requireCase(tenantId, projectId, key.longValue());
    }

    public Map<String, Object> getCase(String tenantId, String projectId, long id) {
        guardProject(tenantId, projectId);
        List<Map<String, Object>> rows = jdbcTemplate.query(String.format(SELECT_ONE_SQL, ROW_PROJECTION_SQL, BASE_FROM_SQL),
                (rs, rowNum) -> toRowMap(
                        rs.getLong("ID"),
                        rs.getString("TITLE"),
                        rs.getString("STATUS"),
                        rs.getInt("PRIORITY"),
                        rs.getBigDecimal("AMOUNT"),
                        rs.getBigDecimal("THRESHOLD"),
                rs.getBigDecimal("AMOUNT_DELTA"),
                        rs.getString("CATEGORY"),
                        rs.getTimestamp("CREATED_AT"),
                        rs.getTimestamp("UPDATED_AT")
                ),
                tenantId, projectId, id);
        return rows.isEmpty() ? null : rows.get(0);
    }

    @Transactional
    public Map<String, Object> updateCase(String tenantId, String projectId, long id, Map<String, Object> patch) {
        guardProject(tenantId, projectId);
        Map<String, Object> existing = requireCase(tenantId, projectId, id);
        Map<String, Object> merged = new LinkedHashMap<>();
        merged.put("title", patch.containsKey("title") ? patch.get("title") : existing.get("title"));
        merged.put("status", patch.containsKey("status") ? patch.get("status") : existing.get("status"));
        merged.put("priority", patch.containsKey("priority") ? patch.get("priority") : existing.get("priority"));
        merged.put("amount", patch.containsKey("amount") ? patch.get("amount") : existing.get("amount"));
        merged.put("threshold", patch.containsKey("threshold") ? patch.get("threshold") : existing.get("threshold"));
        merged.put("category", patch.containsKey("category") ? patch.get("category") : existing.get("category"));

        Map<String, Object> normalized = normalizePayload(merged, false);
        int updated = jdbcTemplate.update(UPDATE_SQL,
                normalized.get("title"),
                normalized.get("status"),
                normalized.get("priority"),
                normalized.get("amount"),
                normalized.get("threshold"),
                normalized.get("category"),
                Timestamp.from(Instant.now()),
                tenantId,
                projectId,
                id);

        if (updated == 0) {
            throw new NoSuchElementException("过滤用例不存在: " + id);
        }
        return requireCase(tenantId, projectId, id);
    }

    @Transactional
    public void deleteCase(String tenantId, String projectId, long id) {
        guardProject(tenantId, projectId);
        int deleted = jdbcTemplate.update(DELETE_SQL, tenantId, projectId, id);
        if (deleted == 0) {
            throw new NoSuchElementException("过滤用例不存在: " + id);
        }
    }

    public Map<String, Object> queryCases(String tenantId, String projectId, Map<String, Object> query) {
        guardProject(tenantId, projectId);
        int page = readPositiveInt(query.get("page"), 1, "page");
        int pageSize = readPositiveInt(query.get("pageSize"), 20, "pageSize");
        String sort = query.get("sort") instanceof String sortExpr ? sortExpr.trim() : "";
        Object filter = query.get("filter");

        SqlFragment whereFragment = filterExpressionSqlBuilder.buildWhere(filter);
        List<Object> baseArgs = new ArrayList<>();
        baseArgs.add(tenantId);
        baseArgs.add(projectId);
        baseArgs.addAll(whereFragment.parameters());

        Integer totalValue = jdbcTemplate.queryForObject(
            String.format(COUNT_SQL, BASE_FROM_SQL) + buildWhereSuffix(whereFragment),
            Integer.class,
            baseArgs.toArray()
        );
        int total = totalValue == null ? 0 : totalValue;

        List<Object> queryArgs = new ArrayList<>(baseArgs);
        queryArgs.add(pageSize);
        queryArgs.add((page - 1) * pageSize);

        List<Map<String, Object>> rows = jdbcTemplate.query(
            String.format(SELECT_ALL_SQL, ROW_PROJECTION_SQL, BASE_FROM_SQL)
                + buildWhereSuffix(whereFragment)
                + filterExpressionSqlBuilder.buildOrderBy(sort, "ID")
                + " LIMIT ? OFFSET ?",
                (rs, rowNum) -> toRowMap(
                        rs.getLong("ID"),
                        rs.getString("TITLE"),
                        rs.getString("STATUS"),
                        rs.getInt("PRIORITY"),
                        rs.getBigDecimal("AMOUNT"),
                        rs.getBigDecimal("THRESHOLD"),
                rs.getBigDecimal("AMOUNT_DELTA"),
                        rs.getString("CATEGORY"),
                        rs.getTimestamp("CREATED_AT"),
                        rs.getTimestamp("UPDATED_AT")
                ),
            queryArgs.toArray());

        Map<String, Object> result = new LinkedHashMap<>();
        result.put("rows", rows);
        result.put("total", total);
        result.put("page", page);
        result.put("pageSize", pageSize);
        return result;
    }

        private String buildWhereSuffix(SqlFragment fragment) {
        return fragment.sql().isBlank() ? "" : " AND " + fragment.sql();
        }

    private Map<String, Object> requireCase(String tenantId, String projectId, long id) {
        Map<String, Object> row = getCase(tenantId, projectId, id);
        if (row == null) {
            throw new NoSuchElementException("过滤用例不存在: " + id);
        }
        return row;
    }

    private void guardProject(String tenantId, String projectId) {
        if (accessGuardService != null) {
            accessGuardService.requireProjectAccess(tenantId, projectId);
        }
    }

    private Map<String, Object> normalizePayload(Map<String, Object> body, boolean create) {
        String title = readRequiredText(body.get("title"), "title 不能为空");
        String status = readOptionalText(body.get("status"), create ? "draft" : "draft");
        int priority = readInt(body.get("priority"), 0, "priority");
        BigDecimal amount = readDecimal(body.get("amount"), BigDecimal.ZERO, "amount");
        BigDecimal threshold = readDecimal(body.get("threshold"), BigDecimal.ZERO, "threshold");
        String category = readNullableText(body.get("category"));

        Map<String, Object> normalized = new LinkedHashMap<>();
        normalized.put("title", title);
        normalized.put("status", status);
        normalized.put("priority", priority);
        normalized.put("amount", amount);
        normalized.put("threshold", threshold);
        normalized.put("category", category);
        return normalized;
    }

    private int readPositiveInt(Object value, int defaultValue, String fieldName) {
        if (value == null) {
            return defaultValue;
        }
        int result = readInt(value, defaultValue, fieldName);
        if (result <= 0) {
            throw new IllegalArgumentException(fieldName + " 必须为正整数");
        }
        return result;
    }

    private int readInt(Object value, int defaultValue, String fieldName) {
        if (value == null) {
            return defaultValue;
        }
        if (value instanceof Number number) {
            return number.intValue();
        }
        if (value instanceof String str && !str.isBlank()) {
            try {
                return Integer.parseInt(str.trim());
            } catch (NumberFormatException ex) {
                throw new IllegalArgumentException(fieldName + " 必须是整数");
            }
        }
        throw new IllegalArgumentException(fieldName + " 必须是整数");
    }

    private BigDecimal readDecimal(Object value, BigDecimal defaultValue, String fieldName) {
        if (value == null) {
            return defaultValue;
        }
        if (value instanceof BigDecimal bigDecimal) {
            return bigDecimal;
        }
        if (value instanceof Number number) {
            return BigDecimal.valueOf(number.doubleValue());
        }
        if (value instanceof String str && !str.isBlank()) {
            try {
                return new BigDecimal(str.trim());
            } catch (NumberFormatException ex) {
                throw new IllegalArgumentException(fieldName + " 必须是数字");
            }
        }
        throw new IllegalArgumentException(fieldName + " 必须是数字");
    }

    private String readRequiredText(Object value, String errorMessage) {
        if (!(value instanceof String str) || str.isBlank()) {
            throw new IllegalArgumentException(errorMessage);
        }
        return str.trim();
    }

    private String readOptionalText(Object value, String defaultValue) {
        if (value == null) {
            return defaultValue;
        }
        if (!(value instanceof String str)) {
            throw new IllegalArgumentException("文本字段必须是字符串");
        }
        String trimmed = str.trim();
        return trimmed.isEmpty() ? defaultValue : trimmed;
    }

    private String readNullableText(Object value) {
        if (value == null) {
            return null;
        }
        if (!(value instanceof String str)) {
            throw new IllegalArgumentException("文本字段必须是字符串");
        }
        String trimmed = str.trim();
        return trimmed.isEmpty() ? null : trimmed;
    }

    private Map<String, Object> toRowMap(
            long id,
            String title,
            String status,
            int priority,
            BigDecimal amount,
            BigDecimal threshold,
            BigDecimal amountDelta,
            String category,
            Timestamp createdAt,
            Timestamp updatedAt
    ) {
        Map<String, Object> row = new LinkedHashMap<>();
        row.put("id", id);
        row.put("title", title);
        row.put("status", status);
        row.put("priority", priority);
        row.put("amount", amount);
        row.put("threshold", threshold);
        row.put("amountDelta", amountDelta);
        row.put("category", category);
        row.put("createdAt", createdAt != null ? createdAt.toInstant().toString() : null);
        row.put("updatedAt", updatedAt != null ? updatedAt.toInstant().toString() : null);
        return row;
    }
}
