/**
 * @generated by module-metadata-cli — do not edit.
 *
 * 契约：同名 *.runtime.generated.json 已在 CLI 写入后通过 Draft 2020-12 audit。
 * VCM 提取在生成器 TS 程序内完成；resolveJsonModule 推断为窄字面量，此处一次性断言类型。
 */
import type { ModuleMetadataRuntimeDocument } from '@spark-appworks/spark-ai/modules'
import runtimeDocumentJson from './page-design-module-metadata.runtime.generated.json'

export const pageDesignRuntimeMetadataDocument =
  runtimeDocumentJson as ModuleMetadataRuntimeDocument
